### ISSUE TITLE
Lab 4: compareTo method

### ISSUE THREAD

**Issue by shecheeyee** [nus-cs2030/2223-s1#100]
Hello, I'm slightly confused regarding the compareTo method, I know how it works theoretically but do not know how to implement it.
My code keeps running into IndexOutOfBoundsException: Index 0 out of bounds for length 0.

For eg, for this test case
> new Booking(new NormalCab("SHA2345", 10), new Request(10, 1, 900))

Do compareTo run everytime the Booking class is called, if yes what is compared to what in this case?

Appreciate any help!

**Comment by mersoncheong** [comment]
Hi! To my knowledge, the compareTo() methods is good when there is a natural ordering within the classes. When the many instances of a classes are instantiated and placed into a `List` ,  you can call `Collections.sort()` and it will order your list based on how you wrote your method

**Comment by OngMinXian** [comment]
class Booking implements Comparable<Booking> {
   ...
   @Override
   public int compareTo(Booking other) {
      ...
   }
}

This is the code provided inside the question. Maybe you can try replacing ... with just return 0 so it returns 0 everytime to check if the error comes from your CompareTo method. 
As for the next step, you can try replacing the return 0 with if, else if, else cases to return -1, 1, 0.

**Comment by YEETTTTTTT** [comment]
hi, I used the provided ImList class to hold my objects, but this causes error when using Collections.sort as Collections.sort() takes in a List not ImList. Do I have to convert ImList into List somehow?

**Comment by MingFengC** [comment]
Hi, `ImList` has its own implementation of `sort()` which takes in a comparator object. Hope it helps :)

**Comment by YEETTTTTTT** [comment]
oh thanks. To confirm, we need to create another comparator class, and don't need to use the compareTo() method?

**Comment by MingFengC** [comment]
Yes you create a comparator class, if you notice the `compareTo()` method already returns -ve int, 0 or +ve int, you can use it in your `compare()` method in the comparator.

**Comment by shecheeyee** [comment]
All good, found the issue, thanks guys!
