### ISSUE TITLE
Lab 4 : Codecrunch Discrepancy in Running code

### ISSUE THREAD

**Issue by EkMi00** [nus-cs2030/2223-s1#104]
# Summary

Why is my code not running properly on codecrunch?

## Description:

I have been stuck on this for the entire time, codecrunch is seemingly running, I assume, compareTo method in level 3 differently than expected. Seemingly, the jsh script on codecrunch is not sorting at all. I have ran the code on jshell multiple times and yet I do not understand why this keeps happening.

## Code Snippets

Attach code snippets (if any)

## Screenshots
![Screenshot (476)](https://user-images.githubusercontent.com/110707998/191409659-d600dfce-a4a8-43e2-bbd2-6964539a3218.png)

**Comment by hongming321** [comment]
Seems like your output is sorted in increasing waiting time, followed by increasing fare

**Comment by yeoxiongyun** [comment]
How do you know what is happening if you do not have the code to test3.jsh? Can you elaborate on how a test affects how the method is running in your code?

Is it possible that you have implemented the compareTo method incorrectly? (aka does b3.compareTo(b4) < 0 returns true in the level 3 test case.)

**Comment by EkMi00** [comment]
> 

I dont know test3.jsh of course, but I expected the way that the sort happens in some direction.

My implementation of compareTo is simply comparing the cheapest fare of both bookings, say D = (fareA - fareB) and return a negative integer if D < 0, positive integer if D > 0, then similarly for waiting time for the tiebreaker. 

Assuming the test3.jsh script is the same as the questions test case, yes b3.compareTo(b4) < 0 did return true.

**Comment by yeoxiongyun** [comment]
The sort happens in the direction of the tiebreaker. So for (sort by cheaper -> then sort by faster), the sorting by fares should either return +ve, -ve or 0. The waiting time will be the tiebreaker when D == 0.

**Comment by EkMi00** [comment]
Oh I see it now, it was because my variable names were flipped, that caused the sort to happen with the tiebreaker first, then the fare, thank you so much
