### ISSUE TITLE
Unable to clear Lab 04 Level 3

### ISSUE THREAD

**Issue by yqlok17** [nus-cs2030/2223-s1#109]
Currently unable to pass Level 3 of this lab due to failing the test case (attached screenshot below).

From the output it seems that the order of test cases should be sorted out by the fares first, followed by the waiting time. However my output is currently sorting the test cases by waiting time first, then the fares. Not sure if it's due to the implementation of my compareTo method. Currently I have hardcoded the compareTo method for all five cases (check if this Booking is cheaper/more expensive than the other Booking and return -1/1 respectively, then check if this Booking's waiting time is shorter/longer and return -1/1 respectively, and return zero if both basis of comparisons are true). 

![image](https://user-images.githubusercontent.com/113164119/191581018-588b20a7-8862-45e4-abac-60b07a972d9e.png)

**Comment by renachongpq** [comment]
Hello!
Your output seems to be similar to #104  , looks like it is sorted by waiting time first followed by fare. You might want to check if you have flipped any variables or did anything in `compareTo` that made it sort by waiting time first.

**Comment by yqlok17** [comment]
Understand the sort is supposed to happen in the direction of the tiebreaker.

Currently I'm able to pass the earlier cases (b3.compareTo(b4) < 0 is returning true). 

Understand the logic is something like: if fareDifference != 0, return the fareDifference, then compare the waitingTimeDifference if fareDifference is zero. Just stuck on the implementation.

**Comment by mohddanesh** [comment]
You shouldn't hardcoded the compareTo method since it won't work for level 5. can yon share more detail with the implementation since your comparison logic seems to right

**Comment by yqlok17** [comment]
Currently my Booking class has its driver and the request as properties. Within the booking I have two methods (cheaperService and cheaperFare) to ascertain which service and its respective fare is cheaper (returns the second service/fare if equal).

For the comparator I set the fare and waiting times for this Booking and the other Booking to four different variables (fare1, fare2, waitingTime1, waitingTime2). The 1 and 2 correspond to this Booking and the other Booking respectively. Then I checked if fare1 != fare2, and return fare1-fare2 if so. If tied, I would return waitingTime1 - waitingTime2 (based off the example from my tutorial's lab slides).

**Comment by yeoxiongyun** [comment]
> EDIT: have tried setting the cheaper service/fare and waiting time as properties and the test cases for level 3 have been passed. Why does using methods to get the cheaper service/fare and waiting time not return the correct outcome but setting them as properties work?

It could be a variable-naming issue aka a typo or 2. The implementation also affects how your code works but I’m guessing the methods may contain the typos.

**Comment by KEEWEIKUANG** [comment]
Personally for me, ive also hit level3 codecrunch error. In my case, its because of my Comparable method whereby there are some logic problem to it. From your test case, it looks like you are sorting based on your Time as your priority, which is not the case because the lower fare should be the priority. Below is the rough idea that i implemented, there should be more things in the code, but the general idea is let your fare be the priority.

if (this.fare == other.fare) 
    if(this.waitingtime < other.waitingtime)
       return -1

**Comment by glendon29** [comment]
idk if it helps but maybe u can just change ur checker in the compareTo method such that if the price diff is not 0 then u return the price diff if not just return the time diff

**Comment by bransometan** [comment]
I think for compareTo() method, you should use it to compare the fares for each booking. Then, what you can do is create a method that return the best service for each booking (this can be done by finding the cheapest fare out of all services for a booking).  Then you can get the best fare (out of the two booking) by using the compareTo() method by comparing the cheapest fare for each respective booking.

**Comment by mohddanesh** [comment]
> EDIT: have tried setting the cheaper service/fare and waiting time as properties and the test cases for level 3 have been passed. Why does using methods to get the cheaper service/fare and waiting time not return the correct outcome but setting them as properties work?

I also think that both ways work. There may be some bugs in the method.

**Comment by zhuyifu** [comment]
seems that you are sorting waiting time before fare, try to reverse

**Comment by ZYN2122** [comment]
I ran into a similar problem previously. Look into your compareTo method, because your methods may still be calling upon the same value for example even if you were trying to call something different.
