### ISSUE TITLE
Question regarded to malformed floating point literal 

### ISSUE THREAD

**Issue by KEEWEIKUANG** [nus-cs2030/2223-s1#11]
Hello, anyone has experienced an error know as malformed floating point literal when calling:

class Circle {
   private static final double EPSILON = 1e-15;
   ...
<img width="303" alt="Screenshot 2022-08-27 015135" src="https://user-images.githubusercontent.com/98325942/186963399-3a32574d-faec-4b3b-8d2c-74aab687a260.png">
}

**Comment by eLTehh** [comment]
Could you try removing the space between the "e" and the "-"?

**Comment by KEEWEIKUANG** [comment]
> Could you try removing the space between the "e" and the "-"?
> 
> So:
> 
> ```
> private static final double EPSILON = 1e-15;
> ```
> 
> The compiler seems to interpret the "1e" as something else (maybe a hexadecimal, unsure) when you add the space. Removing it seems to fix the issue for me.

Thank you so much! Appreciate it :)
