### ISSUE TITLE
Lab04 level5.jsh

### ISSUE THREAD

**Issue by zhuyifu** [nus-cs2030/2223-s1#110]
## Description:
for level5.jsh, what is the return type for the FindBestBooking function, do I just Systems.out.println the bookings in the correct sequence?

## Screenshots

![image](https://user-images.githubusercontent.com/86777618/191707419-88a32820-41e2-455d-81f1-170bc19213fb.png)

**Comment by hongming321** [comment]
It should be `void findBestBooking()` and the method will print out the statements using `System.out.println()`
