### ISSUE TITLE
Level 5; help with printing out each ride on a new line

### ISSUE THREAD

**Issue by anniedaang** [nus-cs2030/2223-s1#113]
# Summary

I've managed to sort my list of all fare option but I am unsure on how to return each of the options on a new line. 
## Description:
At the moment, my output looks like the one down below. Can someone just give me a hint on how to approach the problem? Can I use System.out.printIn or is there another approach on how return each option on new lines and not as a whole list?

<img width="627" alt="Skärmavbild 2022-09-22 kl  23 30 54" src="https://user-images.githubusercontent.com/71130637/191789439-f0fdba3f-d0c9-4f1c-b182-972809302e97.png">
<img width="917" alt="Skärmavbild 2022-09-22 kl  23 27 40" src="https://user-images.githubusercontent.com/71130637/191789516-8f60f415-6e1d-4705-97b1-7df5bd0462ed.png">

**Comment by joeyHXD** [comment]
I used a void method and did System.out.println and it passed the test

**Comment by hongming321** [comment]
#92 had the same issue, you might want to check it out

**Comment by keefetok** [comment]
you are currently returning a sortedlist, which in turn is a list that is sorted using the comparator implemented

what you want is a string, and usually in .jsh files, at least I personally would run void classes because there is no need for a return. Hope this helps!

**Comment by wilsonwid** [comment]
I think there is the possibility to return a single `String` and add newline characters (`\n`) to the end of each line that you want to 'print'.

**Comment by glendon29** [comment]
for me i use void then system printline inside the while loop

**Comment by zhuyifu** [comment]
the easiest way should be using a for loop to loop through and System.out.println()

**Comment by liAiyujelly** [comment]
I used a for loop to loop through the list and used System.out.println() for output! And for the method I used void so do not need to return anything

**Comment by OliverChen0602** [comment]
I passed the test cases by using a for loop to print out the sorted bookings sequentially with System.out.println().
