### ISSUE TITLE
practice 4, Grid2D add() method, how to make new List without ArrayList

### ISSUE THREAD

**Issue by joeyHXD** [nus-cs2030/2223-s1#114]
I've completed the whole practice without ImList and then I ran into this. 
![image](https://user-images.githubusercontent.com/68325229/191790080-a8a186ab-7744-4e0d-86c6-6e5f51d4f851.png)
So how do you return a new Grid2D without using a ArrayList library?
especially when level 1 specified 

> a constructor Grid2D(**List<E> list**, int numOfCols)

so you cant pass a ImList into it.
Do i write another constructor that takes in ImList?

**Comment by xuan-jun** [comment]
Hello, yes you are right! I used another overloaded constructor that took in ImList and it worked
