### ISSUE TITLE
Exercise 4 Level 4 Puzzle class

### ISSUE THREAD

**Issue by giorgiocana** [nus-cs2030/2223-s1#116]
Hi, I'm not sure how to implement the puzzle class correctly. We are supposed to use the super method to create a grid of NxN dimensions. However, this grid includes both strings (the final point ".") and integers, so I'm not so sure how to implement it without mixing up the types... Should I use something like Grid<? extends Object>, or is there a way to avoid this problem?

Also, the class requires us to perform some computations to get a list with the correct elements of the grid. But the super method is to be called first, so how do we create a list containing all the numbers and characters needed for the grid?

**Comment by rachelsitoh** [comment]
I used a fixed number to represent the final point ".", therefore the Grid only has integers. To print out the final point in toString, just convert the fixed number back to ".".
To create the list containing all the numbers needed for the grid, you can try writing a method in Puzzle that returns you a Grid.

**Comment by jingyiiiiz** [comment]
Hi, what I did was to declare the corresponding grid as a variable of the puzzle, and to update the grid accordingly when updating the puzzles. I've also chosen a fixed number (I used 0) so that all contained in the grid are Integers. You can add an if-else to print out the dot of the element is the fixed number you have chosen.

**Comment by wilsonwid** [comment]
I used the `String` class to represent the elements of the `Grid` because there was a `.`, but looking at other people's answers, I think they are valid too!

**Comment by valerietanhx** [comment]
Hello! Just to add on, I don't think we are required to use the super method—I didn't and my code was accepted. Maybe you could have Puzzle as an entirely separate class (that just happens to use the Grid2D class) to avoid the issue of the super method needing to be called first!

**Comment by wilsonwid** [comment]
I think that works best! `Puzzle` itself is not conceptually a `Grid2D`, but rather it uses the format of a `Grid2D` to act as a means to store its state.

**Comment by mohddanesh** [comment]
It is good to implement Puzzle with a Grid2D property and use another number to represent the "."

**Comment by BigheartSmallbrain** [comment]
> It is good to implement Puzzle with a Grid2D property and use another number to represent the "."

I think we are supposed to use the Grid2D class to simulate our puzzle, and yes if u declare ur Grid2D as an integer type(not sure how it works for other types), you can choose a specific integer as your representation of "." for your toString() method.

**Comment by OliverChen0602** [comment]
Hi I used a Grid2D<String> since we can use String.valueOf() to obtain a string version of all numbers in the puzzle, so it is fine to have everything as String.
