### ISSUE TITLE
Exercise 3 Unable to get the correct output

### ISSUE THREAD

**Issue by BlabbyDuck** [nus-cs2030/2223-s1#117]
When I try to find the volume of sphere, my code never multiply the value by 4/3 even though I stated in the code. Anyone know why 

My output
<img width="253" alt="Screenshot 2022-09-23 at 10 40 24 PM" src="https://user-images.githubusercontent.com/108108396/191986616-b1634fa3-dad3-4130-9572-645f57855cf1.png">
My code
<img width="359" alt="Screenshot 2022-09-23 at 10 40 50 PM" src="https://user-images.githubusercontent.com/108108396/191986708-4bffee85-06df-4784-b59e-a1032e404f69.png">

<img width="581" alt="Screenshot 2022-09-23 at 10 40 59 PM" src="https://user-images.githubusercontent.com/108108396/191986727-0eea8aea-6c5f-4670-b3ca-6cef664d369e.png">

**Comment by hongming321** [comment]
Hint: Enter jshell, type `double ratio = 4 / 3` and see what the output is.

**Comment by rachelsitoh** [comment]
/ gives you integer division in java, try type casting in order to get the full value with decimal.
