### ISSUE TITLE
Do ImList pass by reference?

### ISSUE THREAD

**Issue by wjiayis** [nus-cs2030/2223-s1#119]
I want to have one ```ImList<Server>```. If I initialise one ImList in the ```Simulator``` class and pass it as a parameter into each ```Event``` class (and update the ImList from the ```Event``` class), is a common ImList being updated or just a copy?

Thanks in advance!

**Comment by wjiayis** [comment]
Realised that there isn't a need to pass the entire ImList in anyway.

**Comment by ziyi105** [comment]
Just FYI, the ImList will be passed in as a reference, but since it is immutable, even if you update it within event class, the imlist in stimulator class will not be affected as the ImList in stimulator class is still pointing to the original ImList address.
