### ISSUE TITLE
self-exercise #3: 3D Shapes (level 6)

### ISSUE THREAD

**Issue by anniedaang** [nus-cs2030/2223-s1#120]
**I can't pass the last level in the self-exercise #3: 3D Shapes, specifically the last line of code (attached below):**

`jshell> shape = solid
shape ==> solid-cuboid [2.00 x 2.00 x 2.00] with a mass of 4.00`

<img width="489" alt="Skärmavbild 2022-09-25 kl  01 17 57" src="https://user-images.githubusercontent.com/71130637/192110725-71d0d601-0767-48a5-aa3d-ab6e25c5fd40.png">

<img width="1022" alt="Skärmavbild 2022-09-25 kl  01 19 27" src="https://user-images.githubusercontent.com/71130637/192110720-dedfd11e-c1a3-405c-8af3-654e888f71fc.png">

I might have implemented the classes wrong so my question is where in the steps below did I do wrong?

- Create an interface, let's call it Solid, with the method specifications for mass and volume. The SolidImpl class can now be an implementation of Solid.

<img width="407" alt="Skärmavbild 2022-09-25 kl  01 25 52" src="https://user-images.githubusercontent.com/71130637/192110983-1877799c-3073-46ff-b622-582f56e11e24.png">

- Let the SolidCuboid class inherit from Cuboid and implement the Solid interface.

<img width="429" alt="Skärmavbild 2022-09-25 kl  01 25 32" src="https://user-images.githubusercontent.com/71130637/192110971-a45cc235-7792-4daa-8a86-3eb654887827.png">

- Within SolidCuboid, delegate the computation of mass to a SolidImpl property in the class.

<img width="508" alt="Skärmavbild 2022-09-25 kl  01 25 02" src="https://user-images.githubusercontent.com/71130637/192110954-0e8e6d9a-55b8-4264-a263-6325166ada66.png">

**Comment by GarlicButterSteak** [comment]
Hey! I can't remember the exact details of the exercise but I think you just need to let Solid extend Shape3D, hope this will work for you!

**Comment by anniedaang** [comment]
> Hey Annie, I have this issue too, how did you resolve it?

I solved this by having the Solid interface extend Shape3D!
