### ISSUE TITLE
Project Styling

### ISSUE THREAD

**Issue by picaindahouse** [nus-cs2030/2223-s1#123]
Just wish to clarify what will be checked in regards to style for the Project.

Specifically, do we need to create comments to explain what parts of our code do and will the use of protected or getters be penalized?

Thanks

**Comment by wjiayis** [comment]
Hi,

I think the check style for the project is the same as that of our labs.

**Comment by emto17ab** [comment]
Believe comments are not needed, but highly encouraged as they increase readability and also make it easier for yourself to track your code when you have not worked on it for a while and the project grows larger. Check the style guide that is posted here on gitbut on the wiki. In terms of getters as far as I have understood it, they cannot be completely avoided, but should be limited as much as possible to not violate the tell-dont ask principle

**Comment by picaindahouse** [comment]
Thank you! Will look go check the style guide as well!
