### ISSUE TITLE
How to update a specific server

### ISSUE THREAD

**Issue by wjiayis** [nus-cs2030/2223-s1#126]
Hi there,

In my code I have such a structure:
- Arrive and Leave have Customer and time attributes
- Wait, Serve and Done have Customer, Server and time attributes

The logic for allocating the correct server is performed in Simulator as well as in Arrive's nextEvent() function. I store an ImList of servers in Simulator and get nextEvent() to return Pair<Event, Server> to keep it updated.

Hence, in my Serve (from Wait) and Done event, I will need to know which server the event is attached to, and feed it the updated server (of the same server). However, I can't call getServer() because Arrive and Leave do not have Server. May I know how I could resolve this, or am I going in the wrong direction?

Thanks in advance!

**Comment by zandratay** [comment]
Hello, 
For me i had a Pair<Customer, Serve> instead, and i added a String parameter in Customer that stores the current event e.g. "Arrive", "Leave" and updated where necessary. Hope it helps!

**Comment by wilsonwid** [comment]
Another possibility is to use a `List` of `Server`s and have an `id` associated to said `Server`. You can then implement a function inside each type of `Event` to update the list accordingly.
