### ISSUE TITLE
Exercise 4 Level 5 - .equals() comparison is not working

### ISSUE THREAD

**Issue by yqlok17** [nus-cs2030/2223-s1#128]
I'm currently not able to assign my index of the dot ".". My code is as follows:

```
int indexNum = 0;
int indexDot = 0;

for (int i = 0; i < (numOfCols * numOfCols) - 1; i++) {
            if (puzzleList.get(i).equals(".")) {
                indexDot = i;
            }
            if (puzzleList.get(i).equals(numToMove)) {
                indexNum = i;
            }
        }

```

Then when I checked the index numbers using the CodeCrunch test case with new Puzzle(4).move(12), IndexNum was working as it printed "11" when printed but IndexDot remained zero, and hence the positions of 12 and "." could not be swapped.

I'm not sure why my .equals() comparison method is not working. Is there a particular way in my implementation that caused it to not work happen? I have not overridden the method. Would appreciate any help on this.

**Comment by MingFengC** [comment]
In the for loop, your conditional check `(numOfCols * numOfCols) - 1` returns 15 in this case, since the initial position of "." is at index 15, your loop will never enter the first if-else check.

**Comment by yqlok17** [comment]
Thank you! Turns out it was just a careless error :/
