### ISSUE TITLE
Can we make queues (issue of mutability)

### ISSUE THREAD

**Issue by wjiayis** [nus-cs2030/2223-s1#13]
Hi there,

I'm trying to do Exercise 2, and I thought having a queue would be rather useful. Are we banned from doing so since queues are mutable?

Thanks in advance!

**Comment by XihuaZ** [comment]
Were u able to solve the question with Queue?

**Comment by wjiayis** [comment]
Hi XinhuaZ,

I managed to solve the question with an integer tracker instead. I think some hints are:
- Cruises enter in chronological order
- At any point in time, a loader can only serve one cruise (i.e., there will be a situation where loaders 1 & 2 serve Cruise A and loaders 3 serves cruise B)
