### ISSUE TITLE
Exercise 4 level 2 unchecked conversion with add()

### ISSUE THREAD

**Issue by ZhuLeYao** [nus-cs2030/2223-s1#130]
When I do 
Grid2D<E> newGrid = new Grid2D(List.of(this.elems.add(e)), this.numOfCols);
it says there is unchecked conversion. How do I convert the ImList back into a list?

**Comment by OngMinXian** [comment]
What I did was to create yet another overloaded constructor that is
Grid2D(ImList<E> list, int numOfCols) { ... }
which would prevent the need to convert ImList back into a list.

**Comment by lanqinggg** [comment]
What i did was also creating an overloaded constructor. It's easy to implement since we store the elements using ImList!

**Comment by bryanolm99** [comment]
You might be getting this error because you did not parameterize `Grid2D`. 
Try doing `Grid2D<Integer> newGrid = new Grid2D<Integer>(.....)`.
