### ISSUE TITLE
Exercise 2 Level 4 - failed test case for serveCruises(cruises, 1)

### ISSUE THREAD

**Issue by lmlmeilin** [nus-cs2030/2223-s1#138]
# Summary
- Able to pass all the other test cases except this. 
What I did was: 
- finding the total arrival time
For the cruises with total arrival time more than 0
- if total arrival time > 0 
- loop through number of loaders required and print service using arrival time
- call the next loader
For the cruises with 0 arrival time in total
- if total arrival time = 0 
- loop through the number of loaders required and print service using time starting from 0 
- call  the next loader
- if i %numOfLoaders == 0 to add up time with service time to the next cycle of loader

## Description:
Understand from another closed issue similar to mine that I have to add an if statement for the case of numOfLoaders = 1, tried the same things as what I did above but still could not solve it. Would appreciate it if anyone could help (to explain the logic in any way). Thanks!

## Screenshots
![Screenshot 2022-09-30 at 1 40 07 AM](https://user-images.githubusercontent.com/92374446/193103904-91baf46b-3fe9-47eb-847e-74a40d2a4ec3.png)

**Comment by bryanolm99** [comment]
> * loop through number of loaders required and print service using arrival time

This might be the logic causing you to print repeated lines where the loader and the time is the same. Saw that you have considered the case where number of loaders is fewer than number of loaders required - did you implement that logic over here?

In my code, I made sure that the number of lines with the same timestamp is limited by the minimum of number of loaders required and number of loaders available. Hope this helps!

**Comment by KEEWEIKUANG** [comment]
I think from the above test case, your timeOfService looks like it is taking the same time as arrivalTime, in this case, you might need to consider to add a serviceTime to it and not just taking the arrivalTime. Hope it helps!
