### ISSUE TITLE
Ex4 level4.jsh

### ISSUE THREAD

**Issue by zclzz** [nus-cs2030/2223-s1#139]
some how i cant pass the last test case? does anyone have any idea what the TC details are?
![image](https://user-images.githubusercontent.com/107348650/193108256-593b1996-b7b7-4f43-a041-c008e3a2225b.png)

**Comment by YEETTTTTTT** [comment]
Hi, I got stuck on this same test case before and tbh I am not sure how I solved it (mostly trial and error) but I changed my code logic that determined the number of times the service time is added and it worked. 

This was the test case input (for the first test case) I created based off the output: List<Cruise> cruises = List.of(new SmallCruise("S1111", 900), new BigCruise("B1112", 901, 120, 50), new BigCruise("B1113", 902, 40, 4500), new SmallCruise("S2030", 1031), new BigCruise("B0001", 1100, 40, 1500), new SmallCruise("S0001", 1130));

**Comment by zclzz** [comment]
Hello! thank u so much for the feedback and the TC!!! may I clarify more on what u meant by counting the num of times service time is added? For me my service times are added based on if there are sufficient loaders available to match the required loaders by the particular cruise, idk how it is coming a min later than the other loaders :(
