### ISSUE TITLE
[PA1] Can't call IsEmpty from ImList provided

### ISSUE THREAD

**Issue by eLTehh** [nus-cs2030/2223-s1#140]
Doing ``javac *.java`` compiled fine in the actual lab session so this is bamboozling me :////
![image](https://user-images.githubusercontent.com/48056361/193248304-d8f6d0a5-e15f-4393-8bde-a00f17893f64.png)

I didn't touch the code at all, but just for proof that the function is there:
![image](https://user-images.githubusercontent.com/48056361/193248346-25c6b2b5-ea6c-4c0d-96ad-b6073e1ebe37.png)

**Comment by wilsonwid** [comment]
Tagging @danqiye1 to make this issue more visible! I think this issue has something to do with CodeCrunch's `ImList<T>`'s implementation but I can't be completely certain.

**Comment by eLTehh** [comment]
Need to import java.util.List;
