### ISSUE TITLE
codecrunch checkstyle

### ISSUE THREAD

**Issue by zhanyi3** [nus-cs2030/2223-s1#144]
hi, I got flagged for using instanceof but I didn't use it anywhere other than defining `equals()` method which should be allowed. I also didn't use any `==` elsewhere so I have no idea what is wrong. Did anyone else face this issue?
<img width="439" alt="Screenshot 2022-10-01 at 2 26 29 AM" src="https://user-images.githubusercontent.com/105008161/193333678-936eea16-d12d-4663-9f92-8732235dadf7.png">
<img width="639" alt="Screenshot 2022-10-01 at 2 26 59 AM" src="https://user-images.githubusercontent.com/105008161/193333749-ce64adfa-6329-468a-8a58-609501da22e0.png">

Submission ID: | 2383902

**Comment by wilsonwid** [comment]
You might want to try making your code for the method as similar to the lecture slides' `equals()` method as possible, i.e. making sure that the method's header and logic is as close as possible to it.

**Comment by zhanyi3** [comment]
I have doubled checked so many times and make sure it is almost identical. other than the return statement under `else if (obj instanceof Host host)` it is actually the same. so I am very perplexed as to what is wrong

**Comment by wilsonwid** [comment]
In this case, I think it might be better to ask your TA about this as they can most likely see your submission!

**Comment by keefetok** [comment]
hi! i think its coz for example: 

in class Paper, you are using obj instanceof Pen pen rather than using obj instanceof Paper paper

**Comment by wilsonwid** [comment]
To add slightly more info, I only made the `equals()` method in the abstract superclasses, so that might be a reason why.

**Comment by Ryan-loves-movies** [comment]
hi! just to add on, I also had this problem. But it seems that just having an overloaded equals(Term) or equals(Host) in my case allows me to pass the test cases so far (?) although I would agree that equals(Object) should still be a better implementation if you could make it work.

**Comment by zhanyi3** [comment]
thx guys. I managed to figure it out

**Comment by chiralcentre** [comment]
@zhanyi3 hi do you mind sharing how you resolved the problem? I am currently facing a similar problem as well.

**Comment by zhanyi3** [comment]
hi @chiralcentre basically what @keefetok said

> hi! i think its coz for example:
> 
> in class Paper, you are using obj instanceof Pen pen rather than using obj instanceof Paper paper

and @wilsonwid said 


> To add slightly more info, I only made the `equals()` method in my superclasses, so that might be a reason why.

are correct. specifically you can't use `obj instanceof Host` in any other class apart from `class Host`
