### ISSUE TITLE
What is ts?

### ISSUE THREAD

**Issue by Ryan-loves-movies** [nus-cs2030/2223-s1#148]
# Summary
Hi, I can't seem to fully understand the eventual mechanics of the classes. I managed to get the same output for all the 5 levels. However, when given the test cases, something crops up?

## Description 
Expected Output
jshell> p1.snd(ts)
$.. ==> pager1 >--snd--> transmit1
Your Output
jshell> p1.snd(ts)
Error:
incompatible types: ...
    p1.snd(ts)
    ^^

Expected Output
jshell> new PagerStub("ps1").snd(r1)
$.. ==> ps1 >--snd--> transmit1
Your Output
jshell> new PagerStub("ps1").snd(r1)
$.. ==> ps1 >--snd--> transmit1

Expected Output
jshell> new PagerStub("ps1").snd(ts)
$.. ==> ps1 >--snd--> transmit1
Your Output
jshell> new PagerStub("ps1").snd(ts)
Error:
incompatible types: ...
    new PagerStub("ps1").snd(ts)
    ^^

From what I understand, my method 
Pager.snd() does not accept any host that is in transmission 
(i.e.
Accepts: r1
Accepts: p1.snd(r1).rcv().ack()
Rejects:  p1.snd(r1)
)
which follows the final level 5 requirements from my understanding.
However, I get stuck on this test case where I am not sure what "ts" is?

**Comment by wilsonwid** [comment]
Your understanding seems correct, however you may need to make your own test case(s) to figure out what type `ts` has and to correct the error in your code.

**Comment by Ryan-loves-movies** [comment]
Ok, just passed the test cases and just wanted to help other who read this in the future.

I failed the test cases because I had my constructor only accept Transmitter (which inherits directly from Host) and had TransmitterAftHand (Transmitter class after handshake is completed) inherit from Transmitter.

This passes all the test cases in the description in CodeCrunch, but doesn't pass the test cases upon upload. It seems they want us to use a more general class in the constructor (would have been helpful to state so in the description of the problem, rather than have an alternative be possible that also passes all the test cases in the description but for which they do not support the implementation of, though I understand this is a PA so maybe that's why it isn't as explicit)
