### ISSUE TITLE
How to settle this test case?

### ISSUE THREAD

**Issue by zandratay** [nus-cs2030/2223-s1#153]
# Summary
Instead of printing the same strings as shown in the screenshot below, the first test case prints out a very long string as shown in the command prompt screenshot. does anyone know how to resolve this? my return type for snd, rcv and acv is of the child class(es) that inherit from Host or Term.

## Screenshots (if any): 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/88842830/193708033-8b661d0c-1984-425f-92e3-6f756e5c7eaf.png">

![photo_6186122971198894592_w](https://user-images.githubusercontent.com/88842830/193708292-dd9a6154-a1e5-4d40-931c-2c2c9937ce7a.jpg)

**Comment by xuan-jun** [comment]
Hello, for this you have to consider what you are passing into your `snd()` method. For the second test case, you are passing in a `Host` that has yet to make any connection and therefore, after the `>--snd-->`, you only have `transmit1 >--rcv-->`.

For the first test case, you are passing in a `Host` that has already established a connection with other terminals. But the connection path between `pager1` and `transmit1` should not be captured when we are trying establish a connection between `pager2` and `transmit1`. (i.e. `pager1 >--snd--> transmit1 >--rcv--> pager1 >--ack--> transmit1`, we should just be having `trasmit1`)

So you can think of what you need to pass into the next constructor after the `snd()` method is called. But note that ultimately `h1` should still contain information about which Terminals it has connected to for the `broadcast()` method

Hope this helps!

**Comment by timotius-jason** [comment]
Hi,

I guess a quick way to settle this is to print the id/name of the Host instead of the entire thing. Note that you might need to violate the tell-don't-ask principle.

Hope this helps!

**Comment by zandratay** [comment]
@timotius-jason Hello jason, but if we just print the id of Host, then wouldn't the string output of p1.snd(r1).rcv().ack() be incorrect>

**Comment by timotius-jason** [comment]
@zandratay what I'm trying to say is, instead of using the host.toString() method in your print statement, you can use the host's id. 

For example, in your case, it prints 
`pager2 >--snd--> **pager1 >--snd--> transmit1 >--rcv--> pager1 >--ack--> transmit1** >--rcv--> pager2 >--ack--> transmit1`

If we use the host id to replace the **bold** part, we should be able to get
`pager2 >--snd--> **transmit1** >--rcv--> pager2 >--ack--> transmit1`
