### ISSUE TITLE
Project Test Case #2

### ISSUE THREAD

**Issue by yqlok17** [nus-cs2030/2223-s1#154]
# Summary
Currently unable to pass Test Case 2.

## Description 
I'm not sure why the customer is not joining the wait queue. I already have a method that checks if the server is available/has an open queue but Customer 4 is being served immediately instead of joining the queue when they should, in theory, join the waiting queue as the server has just begun to serve Customer 2 (Customer 2 served and Customer 4 arrived happen at the same time, 1.5). I've checked my PQ and it is being set to compare event times and then subsequently compare customer numbers if event times are the same. 

## Screenshots (if any): 
The test case is below, for reference.
`2 1
0.500 1.000
0.600 1.000
0.700 1.000
1.500 1.000
1.600 1.000
1.700 1.000`
![image](https://user-images.githubusercontent.com/113164119/193771319-7f798848-348a-438a-81ad-37a61bb294b2.png)

**Comment by zhanyi3** [comment]
hi, just by judging from the output I think most likely it is due to the checking condition of going from `Arrive -> Wait or Serve` I faced similar problem myself and it really can be either the condition or when the customer actually join or leave the queue. I think you can start debugging by code tracing your `execute()` from `Arrive Event` and think about when should the server state be updated. for eg should customer leave from `Serve -> Done` or when `Done` is executed

**Comment by timotius-jason** [comment]
Hi,

Another possible mistake that I can think about is that you did not update the Server correctly after it serves a Customer.

Hope it helps!

**Comment by yqlok17** [comment]
Hi thanks for the suggestions. However I've now run into a different problem - Customer 4 is now leaving immediately without joining the queue. 

Currently my implementation is such that my nextEvent method will return a new Event and Server pair. My server currently uses integers to track the length of their queues, and then the queues would adjust accordingly as long as the length is less than qmax. 

What I did was re-implement the updating of the server's next available time such that the server will not be available until the last customer in the queue is served. I've tried to update the queues in the WaitEvent by decreasing the queue count, but to no avail so far...

**Comment by eLTehh** [comment]
Is the queue count decreasing successfully, BOTH within the class and outside the class? Try debugging with print statements (or an IDE if you're using that).
I remember forgetting to update either of those. It may help to make a separate, universal method for updating queue count to make things easier to keep track of.

**Comment by yqlok17** [comment]
@eLTehh Thanks for the tip!

I've tried running 3.in and 4.in into the simulator as well, and it seems like the problem is very likely the server not being updated outside the Server class, since the cases are returning me outputs like "Customer 1 done serving by 2" when it should be 1. 

Since it works for test case 1 it definitely is not because the server isn't being updated within its own class.

I'll try again by implementing the method to update my ImList of Servers in the Simulator.
