### ISSUE TITLE
confused about broadcast() method

### ISSUE THREAD

**Issue by YEETTTTTTT** [nus-cs2030/2223-s1#159]
## Description 
Hi, I'm confused about the broadcast() method in level 5. I understand that the output is supposed to come from the terminals so my "pager1:beep" is generated by calling a method in the pager class, then I capture all the beeps and string it together in broadcast() method in my host classes. However, the error below occurs. I am confused what this means? is the output not supposed to be string type?

## Screenshots (if any): 

<img width="785" alt="Screenshot 2022-10-04 at 10 31 15 PM" src="https://user-images.githubusercontent.com/51404150/193848369-e78a64f3-d09b-47df-8e38-b90e408ddf2c.png">

**Comment by hongming321** [comment]
Have you tried `System.out.println()` ?

**Comment by YEETTTTTTT** [comment]
oh.. haha I forgot about that, it worked, thank u!
