### ISSUE TITLE
Project #1 Design issue

### ISSUE THREAD

**Issue by giorgiocana** [nus-cs2030/2223-s1#160]
## Description 
Hi, I am stuck on the project design. I have seen some other similar issues but I am still confused on how to update the servers' queues. 

The way I am designing my program is the following: Simulator creates an ImList of servers, then I create a PQ of input Arrive events coming from the input files, each corresponding to a customer arriving. Then, these two objects are passed to another class called Manager.java.
What the manager does is create a PQ<Event> for each Server, which I group together in an ImList.
Then, I start by getting an Arrive event, scanning the servers PQs, and see if there's an idle one, etc.

However, I am not sure on how to update these server PQs as time goes by. Because a new Customer may arrive and see that the PQ is full, while it has actually finished serving the previous customer by that time.

**Comment by GarlicButterSteak** [comment]
I think that you are almost there! As I understand you, the main goal is to have an updated ImList of servers for every time an event is polled from PQ. So I am not sure how your code is organised, but what maybe could be done would be to update the ImList every single time an event is polled. What I did for this is super inelegant and desperate, but hopefully it may be of help. Every time I poll an event from the PQ, I do two things, which can happen in the appropriate order you deem it to be.

The first is to process each event using the latest ImList<Server> from my manager - so my method specification for this is *Event processEvent(ImList<Server> listOfServers)*. This will ensure that every event is processed using the most current list of servers and updated queues. The second thing I did was to have a method that updates the ImList<Server> in the manager, which is as desired. This method of mine is also located within the parent Event class, just as .processEvent was, so the specification is something like *ImList<Server> updateListOfServers(ImList<Server> listOfServers)*. So to recap, in my Event class, I have two methods .processEvent and .updateListOfServers that I call from my manager for every event I poll. As an example, if I poll a Wait event from PQ, I want to add a Serve event back into PQ (first method), and also decrease the queue of my one true managerial ImList of servers (second method).

How the appropriate event times are updated, was a fluke for me, for as you might already predict, it gets a little messy and inelegant cos I sometimes have one or two lines of duplicate code across the two methods, though it gets the job done. Definitely do seek out a more elegant solution, just writing what I have here cos it's Tuesday!

**Comment by mohddanesh** [comment]
You can update the server after each event gets executed by returning in the execute method with your event with the pair function. In your case, you can try update the Manager Class in each execute method and return it to update it generally in the Simulator class

**Comment by jingyiiiiz** [comment]
Hi, I think just as how your nextEvent works (i.e., checking certain conditions and call the next event accordingly), your updateServer can do the same. Btw, what I did was having a class of CounterQueue to store all Servers and within each Server is ImList<Customer> of Customers in the queue. Then I update the waiting queue and/or servers' availabilities accordingly. Hope this helps!

**Comment by bryanolm99** [comment]
> However, I am not sure on how to update these server PQs as time goes by. Because a new Customer may arrive and see that the PQ is full, while it has actually finished serving the previous customer by that time.

Hello! I think this is indeed a problem if you are simply adding the Arrive events to the various servers' PQ immediately before you started processing the other events (Wait, Done, etc.). To ensure that each server's PQ accurately reflects the state of the server's own queue at any time, you would have to actively poll the events when needed and then add the following event (if it exists) to the server's PQ.

You would still require an overarching "meta" PQ as per our previous labs that contains the events from all servers, and iteratively process each event until this PQ is empty. During the processing of each event in this PQ, you can then perform the relevant actions to the appropriate server's PQ. I think this should help you accurately keep track of the state of each server's PQ at any time.

Hopefully this helps!
