### ISSUE TITLE
Is time complexity a factor to consider in the context of our project?

### ISSUE THREAD

**Issue by ShiJiaAo** [nus-cs2030/2223-s1#161]
# Summary
Wondering if the design component of this project's grading will consider time complexity since time complexity is a result of our design decisions.

## Description 
(Assuming I calculated correctly,) my current approach runs at a whopping O(SElogE) time, where S = number of servers and E = number of events. While this already seems unnecessarily big for this project, I have yet to factor in the sloppy string concatenation that I use to produce some of my output. Not my proudest code, but I promise it's honest work.

I can think of a few ways to make it faster, but it would involve a lot of reorganization and exposing some internal properties in my event classes, which I understand is not exactly a good OOP practice. After lots of thinking, I begin to wonder if this is something we even have to think about.

Any opinions would be appreciated. Cheers!

**Comment by mohddanesh** [comment]
I think this module doesn't concern with complexity at all. Maybe this thinking will help you for work in the future

**Comment by wilsonwid** [comment]
The module definitely does not deal with time complexity at all, else all our codes would have TLEd on CodeCrunch already (immutable `ImList` would need `O(n^2)` time to fill with `n` items :O)
