### ISSUE TITLE
Project Test case #8

### ISSUE THREAD

**Issue by giorgiocana** [nus-cs2030/2223-s1#167]
# Summary
Hi, I have been stuck on this test case for quite a while and I can't come up with a solution. My code works with all the inputs from the test files provided in the question script, but for whatever reason I am failing this test case. Any ideas on how to solve this?

## Screenshots (if any): 
![Screenshot 2022-10-05 at 22 38 16](https://user-images.githubusercontent.com/100380492/194089710-eb738ca1-278b-4546-bec7-81b4d3c86115.png)

**Comment by jamielfh** [comment]
Hi there, I faced the same issue as you did! Not sure if we have similar implementations, but what helped me was checking if the differences in my server list before and after an event was done correctly (in my case, I found that my server's next avail time decreased after a Serve event even though it's supposed to remain constant / increase). Hope this helps!

**Comment by kingofburg** [comment]
From the difference in the lines, my best guess is that your implementation is not correct as 7 serves... should be done at 60.00. this might be the issue of your stored time value. my guess is that the server that you're calling for wait is not updated correctly. What I did was that I had two servers, one static and one changing. the 'static' is not truly static, but as its possible for your server to be updated to the wrong time when you call it. hence the 'static' server is the local guiding, whereas there's a 'global' server which skips the serve, and directly went to done (as done is immediately after your serve event), hence, you need to store the done time, not the serve time in 'global' server. You can attain the serve event's time by using a 'local' server

**Comment by SungMatt** [comment]
Check any getTime() implementation you have in your Event classes! Perhaps thats why the Comparator is a little wonky.

**Comment by acekhoon** [comment]
Hello, I have similar issue and it was because 1. my getTime() was not implemented correctly and 2. I did not update the queue of customers waiting wrongly. Check your implementation of time calculation and queue calculation in your respective event classes in order to debug.

**Comment by winston-lim** [comment]
This is likely due to incorrect event timing OR queue state of server. I got some errors as well and what I did was to log the event timings and server states when processing each event and observing what is wrong
