### ISSUE TITLE
Convention of method declaration

### ISSUE THREAD

**Issue by XihuaZ** [nus-cs2030/2223-s1#17]
From my understanding, the public declaration vs no declaration is meant for defining whether a method is accessible by other packages. Since we are not yet dealing with packages, would current convention be to have no declaration or to have a public declaration for the methods?

**Comment by Grauda123** [comment]
Hi, when there are no declarations, the methods will have a 'Default' access modifier. As for what type of access modifier the method would be, I would say that would depend on the what the method is doing. 
For example, a toString() method should be public for the client to be able to see, 
while a method that you might not want the client to see would be private.
