### ISSUE TITLE
Unsure how to only execute the supplier once for each customer 

### ISSUE THREAD

**Issue by FredericChow00** [nus-cs2030/2223-s1#171]
Hi all, currently the nextEvent() method in my ArriveEvent class is calling the get() of my supplier that assigns the service time to a customer if the nextEvent leads to a WaitEvent or ServeEvent. 

However in my Simulator class, the condition in my while loop also always runs the nextEvent() method to check whether or not there is indeed a next event so as to prevent LeaveEvents and DoneEvents from being added back into the PQ. 

This brings up the problem of that whenever my simulator runs the condition for the while loop, it will prematurely execute the .nextEvent of the current event, hence prematurely calling the get() of my supplier and using up the next double input and when the loop contents in the loop get executed, the intended nextEvent() method doesnt take in the correct double input. I am trying to prevent that from happening but am not sure how to do so. 

Does anyone have any suggestions on how I can overcome this? I was thinking of changing the condition for my Simulator's while loop to not include the execution of the nextEvent() method but in that case, I do not know how to check whether or not the nextEvent is NOT a Leave/Done event and prevent it from being added back into the PQ.

**Comment by ongbernice** [comment]
Hi, I think you can have a separate boolean method in each event to check whether there is a next event and use that in the Simulator class instead of checking within your nextEvent() method. Hope this helps!

**Comment by FredericChow00** [comment]
> Hi, I think you can have a separate boolean method in each event to check whether there is a next event and use that in the Simulator class instead of checking within your nextEvent() method. Hope this helps!

Hmm but the issue is that even if I were to create a new method to check if there's a next event, the new method would also still call the nextEvent() method, which would again call the Supplier's get()

**Comment by mohddanesh** [comment]
maybe it is better to call the get for supplier in the serve event class rather than the arrive class. I think using it in the arrive class may cause more complexity

**Comment by wilsonwid** [comment]
I agree with @mohddanesh, you should try your best to put the `Supplier`'s `.get()` method inside the `Serve` event class as doing it this way would mean that when you call `.nextEvent()` it's going to still be 'visible' inside the current iteration of your dequeue and enqueue step.

**Comment by wilsonwid** [comment]
Aside from the above, I feel like Tell-Don't-Ask is more of a 'guideline' -- if you do need to 'break' it (with good reason, of course) then you should, by all means, do it.

**Comment by kohlindy** [comment]
I think you can check whether there is a next event before executing the nextEvent method. In each event, include a method that checks whether it has a next event, for leave and done, you can return a false thus the nextEvent method wont be called.

**Comment by nixonwidjaja** [comment]
We should only do supplier.get() when cust being served, not when arrive or wait
