### ISSUE TITLE
Is caching allowed in Lab 5? 

### ISSUE THREAD

**Issue by limyeechern** [nus-cs2030/2223-s1#172]
# Summary

Can I check if we are allowed to use caching in this lab? My first submission (after lab) got through and codecrunch did not complain about my cache attribute being non final. I did some debugging and tried to resubmit again but this time codecrunch raised this error that my cache attributes are not declared final.

## Screenshots
First submission
<img width="708" alt="image" src="https://user-images.githubusercontent.com/66681646/194684440-3149dc54-1f01-4b1b-a5a8-cb48bca4bc90.png">

Re-submission
<img width="539" alt="image" src="https://user-images.githubusercontent.com/66681646/194684401-03b5c537-daaa-40d9-9654-b59aae3b5d66.png">

**Comment by Wenbo-J** [comment]
the use of cache is allowed, but this whole cache idea should be encapsulated by Lazy

**Comment by Wenbo-J** [comment]
> > the use of cache is allowed, but this whole cache idea should be encapsulated by Lazy
> 
> @Wenbo-J Just came across this, how would you "memoize" the answer? I'm wondering if it's possible with a final customer; or it needs to be modified.

@SungMatt You may try to passing around the cached supplier (that has "memorized" the answer) when needed, the memorization is within the Lazy class
