### ISSUE TITLE
Use of instanceof not allowed for PA1?

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2030/2223-s1#173]
instanceof is used in the walkthrough video but code crunch showed error when i tried submitting my code that used instanceof, anyone knows how to fix this problem?

![image](https://user-images.githubusercontent.com/82555990/194694789-114a45e8-e34e-4a00-8940-6561f9172a6a.png)

my code: 
![image](https://user-images.githubusercontent.com/82555990/194694809-02321650-8232-4b4d-a68a-f04bfadffb9e.png)

**Comment by Wenbo-J** [comment]
Hi there! it is only allowed if the class you are in is the same as the one that follows your instanceof keyword
(this method you are showing must be in the Transmitter class

**Comment by ziyi105** [comment]
does it work if the class extends/implements Transmitter?

**Comment by chiralcentre** [comment]
I have faced a similar issue as you before and unfortunately the .equals() method has to be in the parent class

**Comment by ziyi105** [comment]
oh no... then I have to make a huge change to my code :(

**Comment by ziyi105** [comment]
thank you anyway!
