### ISSUE TITLE
How would the customer 2nd in queue know what time will be his turn to be served?

### ISSUE THREAD

**Issue by FredericChow00** [nus-cs2030/2223-s1#176]
Since the customer will only be assigned his serviceTime the moment he gets served, in a situation where there are many customers in a queue, how would the last customer in queue know when will be his turn to get served? Wouldn't the time of this last customer's ServeEvent depend on knowing the serviceTime of the customers in front of him who are still in queue and hence don't know their serviceTime yet? 

In this case then how would I calculate the time that this last customer's ServeEvent should occur before adding it back into the PQ?

**Comment by BlabbyDuck** [comment]
For me I updated the Service end time of the server after the first customer queues. When the 2nd customer is called, his serving time will be the server's end time. Basically you have to keep updating the servers end time before the next event is called.

**Comment by ShiJiaAo** [comment]
Yeah you don't have to put them into the queue knowing what time they will be served. For me, when i dequeue a customer I create a new Serve event for them based off the time of the latest Done event from their corresponding server

**Comment by bransometan** [comment]
For me, what I did was that only when my customer is to going to be served (either from arrival or waiting), then I just use the supplier.get() and pass the service time into the Done event and update my respective server. Other than that, I did not assign or update any of my Server or Done event.

**Comment by mohddanesh** [comment]
what i did is to let the customers wait one more time to check the server availability so the 2nd in q can gets updated in time before calling its serve event

**Comment by bryanolm99** [comment]
You can add the customer to the server's queue to wait without knowing the time of service. Then when a customer is done, you check the server to see if there is a waiting customer. If there is, you can add a new Serve event for this waiting customer.

**Comment by rachelsitoh** [comment]
All customers have an arrive event. In arrive, you can check if the customer can be served, if yes, then get the service time and you can return a new customer with the added service time by overloading the constructor.

**Comment by jingyiiiiz** [comment]
I think service time is only extracted when the service event is processed.

**Comment by winston-lim** [comment]
The way i did this is:
1. Each server always keeps track of the time he/she is busy until busy until - which is accessible with `getBusyUntil()`
2. Arrive, Wait and Serve are different events
3. The time a wait event should be processed is just at the instant of time when arrives
4. The time a serve event should be processed is simply the value of `server.getBusyUntil()` at that instant of time + the 
 customer's service duration

**Comment by BBBoyu** [comment]
What I did is to return another waitEvent from a waitEvent. When a waitEvent is called, check whether it can be served. If cannot, continue returning a waitEvent until the next time period.

**Comment by kohlindy** [comment]
I introduced a method called anotherNext() which is called when the server has two customers in the waitingList. So I will call a done event for the first customer in the waiting queue, and another serve event for the second customer in the waiting queue using the anotherNext() method.

**Comment by nixonwidjaja** [comment]
> I introduced a method called anotherNext() which is called when the server has two customers in the waitingList. So I will call a done event for the first customer in the waiting queue, and another serve event for the second customer in the waiting queue using the anotherNext() method.

Not necessarily cyclic dependency if we do this

**Comment by FredericChow00** [comment]
Thank you for all the replies, I have managed to solve it now!
