### ISSUE TITLE
Exercise 5: return type of or method (Level 5)

### ISSUE THREAD

**Issue by bryanolm99** [nus-cs2030/2223-s1#178]
Looking at Java API for `Optional`, the return type of its `or` method is `Optional<T>`. Similarly for `Maybe`, I am assuming that its `or` method should return `Maybe<T>`. 

However, I am getting this compile error:
![image](https://user-images.githubusercontent.com/77519322/194914434-7f879fce-e3e4-43dd-9f26-8cb92a1c0878.png)
 
The compile error can be rectified if I allow `or` to return `Maybe<? extends T>`, but I don't think this is the right approach. Any ideas on how to successfully return a `Maybe<T>`?

**Comment by wilsonwid** [comment]
The right approach is to follow the Java API's method header and to use a function that you have implemented in previous levels to 'force' the return type to be a `Maybe<T>`. The final implementation will be similar to that of `Maybe::map()` with the addition of the aforementioned function.

**Comment by bransometan** [comment]
I think Prof provided a hint at the end of this exercise where he stated that the implementation of the return type must follow Maybe<T>. You need to find a way such that it returns a Maybe<T> instead of Maybe<? extends T>.

**Comment by bryanolm99** [comment]
Appreciate the help!
