### ISSUE TITLE
(Lab05) test case 8: Time Limit Exceeded

### ISSUE THREAD

**Issue by cyiting** [nus-cs2030/2223-s1#179]
Hii, I failed test case 8 because of TLE error and I'm wondering if anyone ran into the same issue.

My approach: 
-.get() is only called in Serve
-Wait returns new Wait if there is more than 1 customer in queue, and the timestamp of Wait is updated each time

:") Any advice will be appreciated :>

**Comment by timotius-jason** [comment]
Hi,

How do you update the timestamp for the Wait event? I believe that if you update it to the server's done time, it should work fine.

**Comment by wilsonwid** [comment]
Aside from that, it may be the case that your `PQ` adds 'duplicate' events into its queue, hence there might be an infinite loop of events that are continually queued and dequeued.

**Comment by cyiting** [comment]
Resolved! Thank you all for your help! 

For anyone wondering, it was because my condition for returning either `Serve` or `Wait` from `Wait` was wrong, resulting in an infinite loop of `Wait` events.
