### ISSUE TITLE
Exercise 5 level 5: incompatible type error

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2030/2223-s1#180]
Hi, does anyone know what's wrong with my code? 

![image](https://user-images.githubusercontent.com/82555990/194997009-2a777d5b-bd22-48ea-af16-dda2ab747461.png)

![image](https://user-images.githubusercontent.com/82555990/194997099-e5ce383e-b0fb-4263-8feb-d69903ade903.png)

isn't integer a subclass of object? Why can't Maybe<Integer> be substituted with Maybe<? extends Object>

**Comment by wilsonwid** [comment]
You might want to see the Java API's method header for `Optional`:
[https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Optional.html](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Optional.html)

Hope this helps!

**Comment by ziyi105** [comment]
oh it works now, thank you so much!
