### ISSUE TITLE
Cannot compile Lazy.java

### ISSUE THREAD

**Issue by dohaduong** [nus-cs2030/2223-s1#185]
# Summary
updated: solved by updating to jdk17

Hi I'm trying to compile Lazy but keep getting this error, does anyone else also have the same issue? I did not change anything in Lazy tho :(
It seems like it's trying to say line 111 Lazy has some syntax error, which is quite strange. I tried changing the codes to "else if (obj instanceof Lazy<?>)" and it worked but then with that I won't be able to use the get method for obj

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://user-images.githubusercontent.com/110105565/195113819-11eaf511-8f19-40c4-9bb0-a018fdf245fd.png)

**Comment by wilsonwid** [comment]
I feel like the error results from a syntax error on the lines above line 111.

**Comment by dohaduong** [comment]
> I feel like the error results from a syntax error on the lines above line 111.

I thought so too and tried to check the lines above and re-download the given file on codecrunch but it still couldn't compile :( but I'll check again! thank you!
