### ISSUE TITLE
Project test case 7

### ISSUE THREAD

**Issue by zclzz** [nus-cs2030/2223-s1#186]
# Summary
Put a summary of the question

## Description 
Hello does anyone knows what corner case test this is? i have been stuck here for quite some time :(
CC says that my output is customer 12 waiting after seeing that 11 is already in the queue of 1. However when I try recreating the TC (black screenshot), I get the correct output?
## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/107348650/195148718-ba39c911-6b87-4972-b3b3-a85f7a2aa700.png)
![image](https://user-images.githubusercontent.com/107348650/195148740-8f10a183-7eda-48d0-a764-9539283a9c84.png)

**Comment by wilsonwid** [comment]
Hi, I think as long as you really only get each customer's service time when they are [beginning to be] served, any implementation should run correctly on CodeCrunch.

**Comment by mohddanesh** [comment]
I think it has to do with how you manage the queue in your server. Maybe you did not update the queue number in time in your wait or arrive event

**Comment by zclzz** [comment]
> I think it has to do with how you manage the queue in your server. Maybe you did not update the queue number in time in your wait or arrive event

Hello, thank you for the feedback, but I tried it with other similar testcases as well and it worked for those test cases, where my simulator was able to update the server Qs everytime a wait event occurs
