### ISSUE TITLE
Cyclic Dependencies in Lab 5

### ISSUE THREAD

**Issue by jamielfh** [nus-cs2030/2223-s1#187]
Hi, anyone faced the issue of cyclic dependencies in Lab 5? My Serve event returns a Done event, but my Done event also returns a Serve event if there is a customer in queue. Would appreciate some help with this!

**Comment by timotius-jason** [comment]
Hi,

I believe using this logic will definitely give a cyclic dependency Serve -> Done -> Serve, unless you can find a workaround. Perhaps trying out other logic would solve this issue. These issue might help: #171 #183
