### ISSUE TITLE
Lab 5 Weird failed test case?

### ISSUE THREAD

**Issue by YEETTTTTTT** [nus-cs2030/2223-s1#189]
# Summary

I failed test case 0 with the following test case output, what does this mean?

## Screenshots

<img width="417" alt="Screenshot 2022-10-12 at 10 29 50 PM" src="https://user-images.githubusercontent.com/51404150/195370814-ed203413-b499-48bb-90e8-e828d2e74f2e.png">

**Comment by Y-ZR** [comment]
Maybe you are printing System.out.println() which is not needed somewhere in your code? Do check it through to ensure it only prints the Events.

**Comment by nixonwidjaja** [comment]
Try to check if you are printing empty line somewhere, maybe when you're debugging

**Comment by acekhoon** [comment]
It might happen because you are returning empty string with \n unnecessarily, or sometimes because of jshell issue in codecrunch.
