### ISSUE TITLE
Error #-200: HTTP Error

### ISSUE THREAD

**Issue by ccheemeng** [nus-cs2030/2223-s1#196]
# Summary

Encountering Error #-200: HTTP Error when uploading files for submission for Lab 6.

## Description:

Has anyone encountered an such an error while uploading files to codecrunch before? This is my first time seeing such an error. To my understanding this is probably caused by some sort of upload size limit, but I'm not completely sure on that. Should I be trying to optimise my approach / do some [code golf](https://code.golf/)?

## Screenshots

![image](https://user-images.githubusercontent.com/95866100/195913456-1bfccb4f-aea0-44a6-a902-3d32699d7546.png)
16 files queued

![image](https://user-images.githubusercontent.com/95866100/195913509-dcffe017-8845-4018-bf50-e377483bafcd.png)
Error #-200: HTTP Error.

![image](https://user-images.githubusercontent.com/95866100/195913533-11dff8a7-29aa-4342-b1cd-a36c34c686c1.png)
15 of 16 files uploaded, Simulator.java (which is not the last file in the queue) is left out, which is confirmed by...

![image](https://user-images.githubusercontent.com/95866100/195914839-94b9bdcd-a7c0-4680-9fe2-d5edb7ad70eb.png)
...the grader not being able to compile Main.java

**Comment by wilsonwid** [comment]
HTTP return code 200 is supposed to be a success though....

**Comment by YEETTTTTTT** [comment]
Hi, if you upload Simulator file first, is it able to be uploaded?

**Comment by SungMatt** [comment]
I suspect it might be a permissions issue. Try running `ls -l` in the folder that you’re uploading from, in your terminal.

**Comment by ccheemeng** [comment]
> I suspect it might be a permissions issue. Try running `ls -l` in the folder that you’re uploading from, in your terminal.

You were right! Something weird happened specifically with `Simulator.java` because I realised I couldn't open it via any external editor. I managed to copy paste the code inside the corrupted file into a new file which could then be submitted. Thanks for the help.
