### ISSUE TITLE
Lab 6 test case 8 

### ISSUE THREAD

**Issue by Nicklelodeon** [nus-cs2030/2223-s1#197]
Hi, I've failed test case 8 for lab 6 with the following error

<img width="429" alt="Screenshot 2022-10-15 at 1 06 18 PM" src="https://user-images.githubusercontent.com/95112058/195969780-cf4847a7-bb53-4db1-b05f-435c8290ec50.png">

From the error, it seems like my queue for server 1 is updating incorrectly (the queue should be full), which is why customer 6 waits at server 1 instead of server 2. However, I'm not sure why im facing this error as I tried creating my own test cases with multiple waiting customers and it still runs correctly.
Currently, my implementation is to store all waiting and currently serving customers into an ImList in server called currQueue. I update this queue in 2 events- Arrive and Done.
1) In Arrive, I first check if the customer can be served immediately. If possible, I will add the customer into my servers currQueue, then return a Serve Event and an updated ImList of servers. 
If the customer cannot be served immediately, I check if the customer can be queued(check currQueue size against maxQueue size (which is the given qmax + 1)) and if possible, I add the customer into my servers currQueue, then return a Wait Event and an updated ImList of servers
2) In Done, I remove the first customer in the servers currQueue, then return an updated ImList of servers.

My implementation seems to work for the prev 7 test cases as well as my own test cases, but I'm not sure why it fails test case 8 specifically. Appreciate any advice given!

**Comment by cyiting** [comment]
Hi i think it may be because your `maxQueue.size` is decremented after the `Done` event is executed, ie while the server is resting, so when you check `currQueue.size < maxQueue.size` it returns true and allows the next customer to wait in line. But when a server is resting, the queue is still full and the next customer shouldn't be able to wait in line.

**Comment by Nicklelodeon** [comment]
ohh I see ok thanks!!
