### ISSUE TITLE
Exercise #6: filter() with two arguments

### ISSUE THREAD

**Issue by wjiayis** [nus-cs2030/2223-s1#198]
Hi there,

I am trying to achieve something like ```.filter((x, y) -> y - x == 2)```. I realised that ```.filter()``` doesn't take in 2 parameters (error message ```incompatible types: incompatible parameter types in lambda expression``` obtained). And while ```reduce()``` takes in a bi-function, it produces just one final value (rather than an ```IntStream```. I believe I must have missed the correct function for this, would appreciate any help!

Thanks in advance:)

**Comment by wilsonwid** [comment]
I assume this is for the Twin Primes task (apologies if my assumption is incorrect). You will simply need to 'iterate' through the values between the range of numbers and 'combine' the filter you mentioned with detecting whether two numbers are primes. Aside from that, a helpful tip is to maybe define an `isPrime(int n)` function similar to what the slides for Lecture 9 did!

**Comment by bryanolm99** [comment]
Agree with @wilsonwid's way to solve the Twin Primes task!

But are there are any methods for streams where we can have visibility of other elements within the stream? In usual for loops this would be easy since we can just access the other elements by indexing but I'm not really sure how we can do this for streams.

**Comment by ginloy** [comment]
You could do:
```
List<Integer> lst = ...
IntStream.range(1,  lst.size()).boxed()
        .filter(i -> lst.get(i - 1) - lst.get(i) == 2)
        .map(i -> lst.get(i))
        .
        .
        .
```
