### ISSUE TITLE
Exercise 6 : Level 4 gameOfLife

### ISSUE THREAD

**Issue by bransometan** [nus-cs2030/2223-s1#199]
Hi guys,

I managed to define the `UnaryOperator<List<Integer>> generateRule()`  method and I could obtain the next generation using `Main.generateRule().apply(list)` but I am unsure of how to apply this to the gameOfLife method to obtain all the different generations based of the integer number of generations `n` of the game. I know that the `list` is the 1st generation, and `rule.apply(list)` will get the 2nd generation, and `rule.apply(rule.apply(list))` will get the 3rd generation, etc. However, I am unsure of how to keep track or obtain these generations by using a stream. Is there any other possible ways that I could approach this question? Thank you!

**Comment by bryanolm99** [comment]
Hi! for generation x, I used `IntStream.range(1, x).boxed().reduce(...)` with a BiFunction that does `rule.apply(list)` to arrive at the required `list` for generation x.

**Comment by bransometan** [comment]
Thanks for your help! I followed your approach and was able to come up with a solution.
