### ISSUE TITLE
Exercise #6: Why is 3 (alone) a twin prime?

### ISSUE THREAD

**Issue by wjiayis** [nus-cs2030/2223-s1#200]
Hi there,

I was doing the question on twin primes, and I'm a bit confused about the last test case. On the one hand, 3 - 2 = 1 which is not a prime, and on the other, 3 + 2 = 5 which is out of range. Would appreciate some hints on why this test case is so.

Thanks in advance!

**Comment by timotius-jason** [comment]
Hi,

I believe that you only need to make sure the number itself (in this case 3) is in range. You do not need to care if the pair (in this case 5) is in or out of range.

**Comment by wjiayis** [comment]
Oh oic, thank you!
