### ISSUE TITLE
Exercise 6: cannot find symbol: IntStream

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2030/2223-s1#201]
Do we need to import anything for stream? I keep getting error saying cannot find symbol when I use IntStream.

![image](https://user-images.githubusercontent.com/82555990/196015120-0c473d7d-8a60-4f23-a636-718d52400e28.png)

**Comment by wjiayis** [comment]
Hi @ziyi105 ,

Yup! ```import java.util.stream.IntStream;```

**Comment by ziyi105** [comment]
alright it works now, thanks!
