### ISSUE TITLE
Linelength issue in code crunch - lab6

### ISSUE THREAD

**Issue by anniedaang** [nus-cs2030/2223-s1#204]
# Summary

I've encountered a compilation issue. Codecrunch complains about one of my lines being too long. How do I resolve this since it's in my constructor?

## Code Snippets
<img width="951" alt="Skärmavbild 2022-10-17 kl  17 42 01" src="https://user-images.githubusercontent.com/71130637/196146799-c8886bab-2ffa-406a-ad9b-41fec3256bc2.png">

## Screenshots
<img width="859" alt="Skärmavbild 2022-10-17 kl  17 48 17" src="https://user-images.githubusercontent.com/71130637/196146668-025b3daf-5ba0-4168-afbb-863eeb8133cc.png">

**Comment by Ryan-loves-movies** [comment]
Constructors can also be split into several lines by each parameter.
i.e.
```
Simulator(int numOfServers,
          int qmax, 
          ImList<Pair<Double, Supplier<Double>>> inputTimes, 
          Supplier<Double> restTimes)
```

**Comment by anniedaang** [comment]
> Simulator(int numOfServers,
>           int qmax, 
>           ImList<Pair<Double, Supplier<Double>>> inputTimes, 
>           Supplier<Double> restTimes)

Thank you for the help!
