### ISSUE TITLE
Exercise #6 Game of Life logic

### ISSUE THREAD

**Issue by wjiayis** [nus-cs2030/2223-s1#205]
Hi there,

I've been stuck on Level 4 for some time, so I decided to reach out for help.

```generateRule()``` is fine. But I am not sure how I should solve ```gameOfLife(...)```. My overall idea was to start with an IntStream of length n, convert it to a Stream of List<Integer> - by executing ```list = rule.apply(list)``` multiple times, and finally convert it to a Stream of String.

To generate the initial IntStream, I used ```.range(...)```. But for the latter parts, I'm really not sure how to approach the problem. I tried ```.iterate(...)```, but it doesn't allow me to perform assignment in the lambda function. I tried creating a new IntStream per generate then using ```.reduce(...)```, but it doesn't seem to work either.

Would appreciate some help/hints on how I should tackle Level 4.

Thanks in advance!

**Comment by kohlindy** [comment]
I use Stream.iterate(list, rule).limit(n).map(.....) . Within the map, I convert each number in the list to "." or "x".

**Comment by danqiye1** [comment]
>But for the latter parts, I'm really not sure how to approach the problem. I tried .iterate(...), but it doesn't allow me to perform assignment in the lambda function.

Can I check what parameters are you passing in to iterate? You should be able to pass your rule to the second argument of iterate.

>I tried creating a new IntStream per generate then using .reduce(...), but it doesn't seem to work either.

I am guessing you can't use reduce because reduce of IntStream takes in BinaryOperator but your rule is a UnaryOperator.

**Comment by wjiayis** [comment]
Solved it, thank you @kohlindy and @danqiye1 :)

**Comment by mersoncheong** [comment]
Hi @kohlindy @axmszr @wjiayis. I am having issues with this implementation. How do you map the List<Interger> into Strings. Thanks!

**Comment by axmszr** [comment]
Hi @mersoncheong! After getting a Stream of Lists containing `"x"`s and `"."`s, I turned each of these Lists into a Stream of the elements (so, overall it's a Stream of Streams of Strings). Then, each of these inner Streams can be reduced into Strings. Hope that helps!

**Comment by mersoncheong** [comment]
> Hi @mersoncheong! After getting a Stream of Lists containing `"x"`s and `"."`s, I turned each of these Lists into a Stream of the elements (so, overall it's a Stream of Streams of Strings). Then, each of these inner Streams can be reduced into Strings. Hope that helps!

Thank you that was helpful!
