### ISSUE TITLE
Test case 2 (Lab6) - issues with statistics 

### ISSUE THREAD

**Issue by anniedaang** [nus-cs2030/2223-s1#207]
# Summary

I encounter a problem with my average wait time in the statistics on test case 2.

<img width="475" alt="Skärmavbild 2022-10-18 kl  19 27 08" src="https://user-images.githubusercontent.com/71130637/196417115-55c50565-fe61-49cd-9984-51c992f5a6d1.png">

## Description:
In my ServeEvent class I increment the waiting time by passing on the current time of the ServeEvent class (the time that the customer get served) along with the customer object.
<img width="658" alt="Skärmavbild 2022-10-18 kl  19 25 49" src="https://user-images.githubusercontent.com/71130637/196416863-97be62ef-b2e1-49f2-afd9-da95f369c578.png">

and in the incrementWaitTime method I subtract the time of of when the customer got served (ServeEvent's current time) with the customer's arrival time to get the total wait time and divide it by the number of customers who got served.
<img width="677" alt="Skärmavbild 2022-10-18 kl  19 26 43" src="https://user-images.githubusercontent.com/71130637/196417022-adc9425f-58d5-4262-bf9a-18d9b46bc283.png">

It looks right to me but maybe I missed something or misplaced the statistics update? Has anyone encountered similar issue and how did you solve it?

**Comment by izascia256** [comment]
I am assuming your updateStats method is in the ServeEvent class, and it is overriding an abstract method from the abstract Event class. So, every single class that you have has an updateStats method.

You might want to check that all of them have the correct method written down, and whether the customer class is being passed into the method correctly, (i.e. i think line 45 should be this.customer)

**Comment by dohaduong** [comment]
I think you could try updating your customer in your Statistic after every updateStats and/or incrementWaitTime to make sure that the current customer is passed in correctly :) personally i think customer could also be included in your Statistic constructor

**Comment by dohaduong** [comment]
I think you could try updating your customer in your Statistic after every updateStats and/or incrementWaitTime to make sure that the current customer is passed in correctly :) personally i think Customer could also be included in your Statistic constructor

**Comment by anniedaang** [comment]
Thank you all for the response! I solved this by calculating the average in the toString() instead of in the incrementWaitTime()
