### ISSUE TITLE
Struggles with test case 5 (lab6)

### ISSUE THREAD

**Issue by anniedaang** [nus-cs2030/2223-s1#210]
# Summary

Has anyone encountered a similar problem in test case 5? I can't seem to find what the problem is in my code.

## Screenshot:
<img width="467" alt="Skärmavbild 2022-10-19 kl  17 54 50" src="https://user-images.githubusercontent.com/71130637/196660157-8ee3150d-dc20-475d-92c0-2c3da3c5db0a.png">

**Comment by wilsonwid** [comment]
It seems that your function is not updating the events inside the priority queue. The issue might lie with how you update the timings of each event after a server has finished serving a previous customer and is currently resting.

**Comment by dohaduong** [comment]
You could try to check if your server/event timing is updated correctly when customer changes from wait -> serve. Personally I think the problem may be when your customer goes from wait to serve, your server's free time is not updated so the next customer in the waiting queue was also served immediately.

**Comment by wilsonwid** [comment]
@dohaduong's suggestion seems legitimate, too! Other than that, there may be a case where your `Serve` event may need to return another `Serve` event if the server is not done serving another customer, or if the server is currently resting.

**Comment by anniedaang** [comment]
> It seems that your function is not updating the events inside the priority queue. The issue might lie with how you update the timings of each event after a server has finished serving a previous customer and is currently resting.

Thank you for the suggestions! I found that the issue was in my BufferEvent where I didn't properly retrieve the server's next available time. Thank you for the help!
