### ISSUE TITLE
Exercise 5: Why am I not able to force the assignment of type using Maybe<R> (Level 6)

### ISSUE THREAD

**Issue by aerodromic** [nus-cs2030/2223-s1#211]
![image](https://user-images.githubusercontent.com/9198061/196659509-bbab4f45-c3b5-4e3a-b6ec-4de7245dc71e.png)
Semi related to #182 and #178. Level 6 can be resolved with type-casting the result (Maybe<R>), but in the spirit of CS2030, it's not allowed. I've tried using a different approach from #182 by trying to reassign the type to Maybe<R> but it does not seem to work. Error message shown is: `error: incompatible types: CAP#1 cannot be converted to Maybe<R>`. I would appreciate any help to clear my misconception.

**Comment by wilsonwid** [comment]
You will need to use one of the functions that you have defined previously in level 5 for the compiler to not complain.

**Comment by bryanolm99** [comment]
My understanding is that `mapper.apply(thing)` returns a `? extends Maybe<? extends R>` which cannot be implicitly casted to a `Maybe<R>` directly (like what you did), but possible to be implicitly casted to a `Maybe<? extends R>`.

**Comment by keefetok** [comment]
like what wilson said, you have to use a previously defined function to help u return the <R> maybe

**Comment by mohddanesh** [comment]
@aerodromic thank you for the links
