### ISSUE TITLE
Exercise 5 level 5, incompatible type 

### ISSUE THREAD

**Issue by KEEWEIKUANG** [nus-cs2030/2223-s1#212]
<img width="487" alt="Screenshot 2022-10-20 104119" src="https://user-images.githubusercontent.com/98325942/196843678-3d8137e4-7e25-4e9c-947f-c67f5ce30c26.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/98325942/196843826-be781a0a-59d9-4073-bf54-f772d5c36a3c.png">

Hi, ive followed the Optional  method, however, how do i force it to change to a Maybe T, so that i do not get the incompatible type error? Appreciate it alot !

**Comment by OngMinXian** [comment]
You can try using the methods you defined earlier to help you convert it. 
Specifically I decided to use orElse since it returns the thing if it is not null and then I convert it back into a Maybe<T> using the of method.

**Comment by wilsonwid** [comment]
I did the same thing as what @OngMinXian said and it worked perfectly!

**Comment by KEEWEIKUANG** [comment]
Thank you guys for your advice!

**Comment by peipeipeiiii** [comment]
I got similar issue and I solved it by casting the supplier.get() to a Maybe<? extends T> first
