### ISSUE TITLE
Extremely confused about what is happening in test case 8 in lab 6

### ISSUE THREAD

**Issue by RezwanAhmed123** [nus-cs2030/2223-s1#213]
Anyone faced a similar issue as me? I'm passing level 7 so I do not think the issue is arising from the rest times itself but I am really confused as to why the served events for the delayed arrive events are not being activated as seen in test case 8. Any idea how to proceed and debug? I created a similar test case to 8 as shown below as well.

## Screenshots

![Test case 8 result](https://user-images.githubusercontent.com/95862073/196966150-d571dcc5-c64c-4aac-b3f6-2df0ab074ef3.png)

## Test case 8
2 1 10 0.8
0.0
1.0
1.205
2.776
3.887
3.910
9.006
9.043
9.105
9.160
1.1
0.2
0.7
0.014
0.154
0.013
1.478
2.593

**Comment by Y-ZR** [comment]
Hi, you missed out a case whereby the after the customer waits, no serve event is produced and pushed into the priority queue.

**Comment by peipeipeiiii** [comment]
Hi I think it's probably because you decrement the queue size before the next serve event is executed. In other words, you should only decrease queue size when the server finished resting. So when customer 6 comes, he would observe that the queue is still full and left the system as the serve event is not carried out yet.

**Comment by bransometan** [comment]
From your error output, I realised that as one of customers is waiting for a particular server, they does not get served later. Maybe you want to check on either your wait or serve event if they are pushed correctly into the queue when the server is taking a break.

**Comment by RezwanAhmed123** [comment]
Thanks all, I managed to debug and solved the issue.

I realised in some special cases the updates were happening more than one step at a time which caused some of the breaks to automatically end causing both updating of queue problems and also not updating the served events if there is a new customer being served. It was solved afterwards thank you!

**Comment by glendon29** [comment]
Hi @RezwanAhmed123 would you mind if you share how you solve this issue. Im currently facing the same issue as you too

**Comment by RezwanAhmed123** [comment]
@glendon29 

for me as others pointed out, sometimes the customer is removed before the done event is created. On top of that the server would be updated in wrong order sometimes because every update loop would try to do many things at once.

I changed each update loop to only handle one thing at one time, for example server A was resting

previously the implementation was that the loop would put A into a non rest mode and then call the get service time for the next customer

in my new implementation the update loop only puts it to non rest mode and then down the line in another loop it would do the next step.
