### ISSUE TITLE
Codecrunch Exercise 1 Importing Streams

### ISSUE THREAD

**Issue by yewey2** [nus-cs2030/2223-s1#214]
Hi, how should I be importing streams when redoing older codecrunch exercises?

I get this error...

![image](https://user-images.githubusercontent.com/83965035/197177906-69c6adad-1d43-4d78-9d71-0e8940c5a814.png)

**Comment by wilsonwid** [comment]
Have you included `import java.util.stream.Stream;` at the top of your jsh file?

**Comment by yewey2** [comment]
yes I did

**Comment by ZYN2122** [comment]
Is your Streams java file in the same folder?

**Comment by yewey2** [comment]
> Is your Streams java file in the same folder?

@ZYN2122 I'm using Stream directly from jdk17 api

**Comment by Ryan-loves-movies** [comment]
Yes, I was also met with the same problem. It seems with .jsh files, the importing doesn't seem to work. 
However, using list.stream() was sufficient.
(whereby list.stream() does not require additional imports)

**Comment by yewey2** [comment]
> Yes, I was also met with the same problem. It seems with .jsh files, the importing doesn't seem to work. However, using list.stream() was sufficient. (whereby list.stream() does not require additional imports)

@Ryan-loves-movies this works, thanks! I've feedbacked to the TAs, hopefully the prof changes it soon
