### ISSUE TITLE
Codecrunch Exercise 4 ImList

### ISSUE THREAD

**Issue by yewey2** [nus-cs2030/2223-s1#215]
I redid exercise 4 with streams, but in my code I used the addAll() function from the newer version of ImList.
I uploaded the newer ImList to codecrunch (with addAll), but it doesn't work.
Is this a bug, or are we not allowed to use the newer ImList?

Here's the screenshot of the problem
![image](https://user-images.githubusercontent.com/83965035/197322186-bb37b553-66f0-48e5-bc6b-6e6b44e2e33e.png)

Or is it some other issue?

**Comment by Ryan-loves-movies** [comment]
Yea, if I'm not wrong the ImList used by the autograder is the original "ImList" and cannot be modified

**Comment by yewey2** [comment]
My TA told me that the prof has updated the ImList to the new one! It should work now (even though I changed my code haha)
