### ISSUE TITLE
Exercise #5: Maybe Too many non-private methods error

### ISSUE THREAD

**Issue by Tsang-Kai** [nus-cs2030/2223-s1#217]
![Screenshot 2022-10-22 165339](https://user-images.githubusercontent.com/110796576/197330625-9ecef7f1-6a8c-4b7d-8e19-d752c2033fcc.png)
I encountered the above error message while uploading my Maybe.java to codecrunch. Which methods should be private to prevent this error? I tried reverting the Maybe constructor from protected to private but it didnt work

**Comment by yeoxiongyun** [comment]
there isn’t anything wrong with the Maybe constructor being protected. Did you add your own methods?

**Comment by Tsang-Kai** [comment]
i added a getThing() method for the equals to work. i need get method to get the "thing" in the other object compared for the equals method to work. is this not allowed?

**Comment by timotius-jason** [comment]
Hi,

I don't think the getThing() method is needed to do the equals() method.

**Comment by yeoxiongyun** [comment]
you are allowed to use "maybe.thing == " so adding a getThing() method is unnecessary.

it's allowed in the sense that your code isn’t breaking any rules, but the rule is there to prevent people from using that loophole to create other methods

**Comment by OngMinXian** [comment]
I at first used a getThing method but actually you can use orElse method since it returns the thing if it is not null and then I convert it back into a Maybe using the of method.

**Comment by ShiJiaAo** [comment]
Got this same problem and solved it by using the orElse method as a substitution for the get method as well. pardon the slight detour but @OngMinXian did you have to pass in a null as the argument to orElse? I had to do that but couldn't find a way around it. All other arguments I could think of failed for me.

**Comment by Tsang-Kai** [comment]
I solved the problem. Since Im just comparing Maybe objects inside Maybe, i can just use other.thing instead of needing to create a get method. Thanks for the suggestion of using orElse!
