### ISSUE TITLE
Codecrunch Exercise 4: Selection Construct Detected

### ISSUE THREAD

**Issue by yewey2** [nus-cs2030/2223-s1#218]
![image](https://user-images.githubusercontent.com/83965035/197344633-55267af6-306e-4f27-8844-b3a87827a173.png)

I changed all my if statements to conditional statements using condition ? if true : if false

But I get this instead
![image](https://user-images.githubusercontent.com/83965035/197344667-6230dcf9-30d7-4a99-a6c0-3ca2cedd28b9.png)

Any hints on how to solve this, or do I really have to make every conditional a Stream of (List of (condition)) and evaluate the final product with reduce?

**Comment by yewey2** [comment]
> Stream of (List of (condition)) and evaluate the final product with reduce

Update: this does not work, please send help 😢

**Comment by Ryan-loves-movies** [comment]
The "if else" and "? :" cannot be used,
Optional() can be used instead. 
```
a = (x > y) ? 55 : 0;
a = Optional.<Integer>of(55).filter(k -> x > y).orElse(0); // Should assign values to "a" similarly
```

**Comment by yewey2** [comment]
Oh I see, I thought we were supposed to use streams all the way... Thank you!
