### ISSUE TITLE
Exercise 6: task 2 and 3

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2030/2223-s1#219]
can someone give me some hints for tasks 2 and 3? I am stuck for many days already and I still have no clue how to solve them :")

**Comment by wjiayis** [comment]
Hi there,

Hint for task 2: Complete```return Stream.<String>of(str.split(""))...``` with a ```.reduce(...)```
Hint for task 3: One way is to count the occurrence of "second occurrences", e.g., 2 3 1 (1) 1 1 3 (3) 3

**Comment by wilsonwid** [comment]
Additional hints:
Task 2 can be a one-liner as it just requires a direct application of what @wjiayis mentioned. Trying to code it out on paper (for some arbitrary point in the original string) might be helpful!

Task 3 might require you to iterate over the indices and devise a linear-time algorithm (i.e. one that passes through the iterated indices once) using `if ... else ...` statements.

**Comment by OngMinXian** [comment]
For task 2 you can try using reduce to return the original string, then change the order of the operands to form the reverse string.
For task 3, i find that I used .boxed() to iterate through the list and then filtering only the numbers that are the first number of any repeated sequence ie. **1** 1 2 **3** 3 1 **2** 2 (the bolded ones) then counting them

Hope this helps!

**Comment by yewey2** [comment]
I think task 2 has been explained pretty well by everyone else. 
Another way around task 3 is to use a filter with a helper function, and the helper function checks whether the next item is the same as itself.
Alternatively, you can iterate through a Pair of (index, Pair of (previous, next)), and check for repeats there

**Comment by ziyi105** [comment]
Thanks for the replies guys! I managed to solve them already!
