### ISSUE TITLE
Queries on lambdas.

### ISSUE THREAD

**Issue by YeoWeiHan123** [nus-cs2030/2223-s1#220]
Hi, I would like to know how to change/set variable in for loops as lambdas, 

```
variableFlag = false;
for (int num : numbers) {
        if (num > maxNum) {
            variableFlag = true;
        }
    }
```
and what about for creating new objects in lambda?
```
for (int num : numbers) {
        if (num > maxNum) {
            Object o = new Object(int num);
        }
    }
```

Thanks!

**Comment by wilsonwid** [comment]
I don't think it's possible to change local variables from inside lambdas, as Java will throw an exception detailing that "variables used in lambda expression need to be final or effectively final".

**Comment by mohddanesh** [comment]
i agree with the above. We can't change the starting element in the stream halfway

**Comment by timotius-jason** [comment]
Hi,

A hacky, but not recommended, way of doing so is to create an array (or any mutable data structure) to store the variable. We can then change the elements of the array from the lambda function.

p.s. this is not a good practice, and should be avoided whenever possible. We are also not allowed to use mutable data structure in this course :)

**Comment by giorgiocana** [comment]
Hi, I agree with the above responses. It is not possible since variables inside lambdas need to be final. Modifying an array works, but I don't think it is allowed for this course.
Are you facing any implementation issues due to this reason?
