### ISSUE TITLE
[Lab 6] Test Case 7 Customer 10

### ISSUE THREAD

**Issue by qwertyKey-s** [nus-cs2030/2223-s1#224]
# Summary

I am stuck at Test Case 7, where Customer 10 is being served earlier than it should be.

## Description:

To implement the rest time, after every `Serve` event, I updated the server's next available time to be `+= server.getRestTime()`. This approach seems to correctly identify that Customer 3 and Customer 4 should be served by Server 2 instead of Server 1. But for some reason, it fails to identify that Customer 10 should be served only when Server 1 has finished resting.

## Screenshots

![testcase7](https://user-images.githubusercontent.com/114850052/197680178-d8ecd157-58f9-4f25-989c-d79cc3887450.jpg)

**Comment by dohaduong** [comment]
I think you could try getting restTime after every Done event instead of Serve event, maybe the reason why your customer 10 was served earlier is that restTime is get in wrong order
