### ISSUE TITLE
Exercise 5 grading codecrunch

### ISSUE THREAD

**Issue by steffffilim** [nus-cs2030/2223-s1#225]
<img width="279" alt="Screenshot 2022-10-25 at 8 45 39 PM" src="https://user-images.githubusercontent.com/113164974/197776937-9f45d56e-4d46-476f-949f-fa968da7ca2f.png">

hi im not sure what does this error mean could someone please explain to me. not too sure what the requirements of codecrunch are! thank you! i am able to get all of the output that are provided on codecrunch but this error that I'm getting does not mark my work at all

**Comment by cherylchan02** [comment]
hi im having the same problem i havent managed to solve it yet but for me the grading works until my level 5 methods i wonder if yours error occurs at the same level. I suspect it is my or method but no matter how i change it nothing seems to work :(

**Comment by Tristanlimyr** [comment]
U can refer to #217. Might be due to getter methods.

**Comment by kohlindy** [comment]
I think only writing methods stated in the exercise will solve the problem.

**Comment by Y-ZR** [comment]
Hello I had faced the same problem with you. The problem may be that you have implemented a helper public method such as a public getter method.

**Comment by peipeipeiiii** [comment]
Hi I faced the same problem. One way to get around this is to make the constructor public so that you don't need additional getters.

**Comment by steffffilim** [comment]
hello yes indeed the fact that getter methods are used in my code caused this error. thank you everyone!
