### ISSUE TITLE
vim difficult to navigate

### ISSUE THREAD

**Issue by Grauda123** [nus-cs2030/2223-s1#227]
Hi,

Whenever I'm trying to do a System.out.println() to debug on vim, the output is too long such that vim is not able to scroll up to view the top output. Anyone have any suggestions to get around this?

**Comment by bonemarr** [comment]
install a JDK debugger u can find it on the wiki tab
some vim shortcuts are: o (open new line), g,h,j,k instead of arrow keys to move between lines, :tabedit to view multiple tabs, gt to switch between tabs

**Comment by amritha2510** [comment]
to debug the continuous output of loops, try adding a break or continue statement!

**Comment by Wenbo-J** [comment]
> install a JDK debugger u can find it on the wiki tab some vim shortcuts are: o (open new line), g,h,j,k instead of arrow keys to move between lines, :tabedit to view multiple tabs, gt to switch between tabs

I think it is h,j,k,l instead of arrow keys

The tabedit is really really really helpful! Thanks a lot for sharing that!

**Comment by mohddanesh** [comment]
you can actually zoom out and open up 2 windows of the same file to display output by "pages"
