### ISSUE TITLE
[Lab 6] Test case 8

### ISSUE THREAD

**Issue by glendon29** [nus-cs2030/2223-s1#230]
![image](https://user-images.githubusercontent.com/29744561/198280807-ddc92501-ea8c-41d9-b5b2-e714bb2739dc.png)

Currently my main issue will be generating the serve event after wait. Based on my implementation back in Lab 5, where  a new Serve event is generated after every Done event of the previous customer for each queuing customer. Since there is a new rest time being added , the issue will be i am unable to generate the Serve after the Wait since the Done event from the previous customer did not capture the waiting customer due to the new Free Time.

Will greatly appreciate any forms of guidance or tips of how to combat this issue

**Comment by izascia256** [comment]
Currently, I think most of us are doing it such that a the Wait Event will generate a Buffer Event on the Server's next available time, then checks whether the Server is free at that point before generating the Serve Event.

For your case, if you are able to generate the Serve Event after the Done Event without cyclic dependency issues, how are you currently deciding on the time at which the Serve Event is generated? Is it possible to feed the rest time into the event time in your case?

**Comment by dohaduong** [comment]
For me, what I did was generate a new DoneRest event from each Done event, and then new Serve event is generated from DoneRest instead of Done :) hope this helps!

**Comment by glendon29** [comment]
hi @dohaduong may i know like what does the DoneRest do ?

**Comment by dohaduong** [comment]
> hi @dohaduong may i know like what does the DoneRest do ?

So basically after Done I just update the server's free time, and then generate a DoneRest that takes in the updated server and the same customer as Done. So when I poll DoneRest from the queue, I will generate the next Serve event with the correct serve time. 
It's basically the same as my Done from lab 5, it's just that my server's free time is now updated.

**Comment by glendon29** [comment]
Managed to fix the issue thanks @dohaduong
