### ISSUE TITLE
Exercise 6 Task 3

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2030/2223-s1#231]
Hii I asked for hints before but I still failed the test case for task 2 :")
I believe my approach is wrong and would really appreciate it if any kind soul can guide me or give me some hints :")

**Comment by wjiayis** [comment]
Hi Ziyi,

Perhaps you could share your current approach, and we can see how it could be tweaked?

**Comment by ziyi105** [comment]
Hello thanks for offering your help! but I finally managed to solve it after so long :"))))
