### ISSUE TITLE
Lab #6: Test Case Failed 

### ISSUE THREAD

**Issue by yqlok17** [nus-cs2030/2223-s1#233]
# Summary

Getting a strange output for the first line in my program.

## Description:

The 2 test cases given on CodeCrunch is giving the exact same output when I did "java Main < test.in" for my code, but I'm getting this strange error where "customer 3 leaves" shows up in the output for some reason on CodeCrunch. Has anyone faced this issue? Would appreciate any assistance with this. 

## Screenshots
![image](https://user-images.githubusercontent.com/113164119/198602753-8e062959-3833-4282-b45f-b21d3982dc91.png)

**Comment by wilsonwid** [comment]
This might be an issue with you prepending the output string from `Simulator::simulate()`.

**Comment by izascia256** [comment]
I am assuming this is the first test case.
Check further down whether the "0.7 customer 3 leaves" appears again.
If it appears again, check whether `Simulator::simulate()` has accidentally added in the String as mentioned by @wilsonwid. If it doesn't appear again, there is a chance your PQ is polling the events in the wrong order.

**Comment by yqlok17** [comment]
Currently I'm adding the events that need to be in the sim to the output string (Arrive, Wait, Serve, Done, Leave) wherever necessary and not any intermediate events (ContinueWait, Rest). I haven't added in any extra strings, so I'm not sure why an output from Lab 3 is appearing.

I'm guessing this error might lie inside my PQ or my comparator? I've been using the exact same comparator since Lab 3.

**Comment by izascia256** [comment]
I just noticed the that the output format was for the older Labs.
For this test case, the expected output is as follows:
![image](https://user-images.githubusercontent.com/112748524/198631893-34959c72-9f24-4f1b-b345-d9556bc65d02.png)

Since this is the only Leave Event that occurs, maybe you might want to check your LeaveEvent Class?

**Comment by wilsonwid** [comment]
@yqlok17 I have also been using the same (or very similar) comparator class since Lab 3. I don't think the issue lies there. I think you might want to check your `LeaveEvent` class as what @izascia256 mentioned.

**Comment by ShiJiaAo** [comment]
I have a feeling your simulator is printing stuff, so that one leave event got printed before the simulator gave the output string to Main

**Comment by yqlok17** [comment]
Thanks everyone. Have checked and it was a silly error on my part - I didn't remove my debugging statement >:(
