### ISSUE TITLE
How to access each Num in a fraction?

### ISSUE THREAD

**Issue by eLTehh** [nus-cs2030/2223-s1#237]
So from my implementation, Fraction extends AbstractNum<Frac>, which means the numbers are contained in an Optional Frac, which is basically a kind of Pair. For add/sub/mul, I assume using OOP principles, we have to make use of the add/sub/mul defined in the Num class. 

e.g. this.numerator.add(otherFraction.numerator)

Through the optional, I can only map the nums contained within the fraction's pair, but I can't access the nums in the other fraction pair with the map function, I think? Since it's wrapped in an Optional. Get is banned. I'm not sure how to go about doing this. Is there a lecture slide I should look at that will hopefully give me some hints?

**Comment by eLTehh** [comment]
Figured it out

do a.flatMap(x -> b.map(y -> y.add(x))) to return a new optional num

**Comment by mohddanesh** [comment]
thanks! your approach helps me a lot
