### ISSUE TITLE
Exercise 6 task 4 test case not following the expected rule?

### ISSUE THREAD

**Issue by zccccclin** [nus-cs2030/2223-s1#242]
Dear all, I just got back the result for exercise 6 and I realise the expected output is not following the desired rule.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/60165401/198869387-1a36067c-ac54-4e9f-b6e0-f40a531a65bd.png">
The alive cell in test case continued to be alive in the next cell in the expected output  in almost every round. Is it a issue with the test case?

**Comment by wjiayis** [comment]
Hi @zccccclin, this test case uses ```rule30``` rather than ```Main.generateRule()```. From the diff, it seems like some logic that is supposed to be in ```Main.generateRule``` is placed in ```Main.gameOfLife``` instead.

**Comment by zccccclin** [comment]
Yeap It was a careless mistake from my side! Thanks for clarifying.
