### ISSUE TITLE
Unchecked or Unsafe Operations

### ISSUE THREAD

**Issue by GarlicButterSteak** [nus-cs2030/2223-s1#246]
## Description:

Hi all, sorry if this is a stupid question as I'm still struggling with FP, but when I finally somehow managed to squeeze something out of my brain for Level 1, I came across these warnings which I do not understand, how can I go about trying to fix it? Or am I doing something wrong here? Thanks for your patience!

## Screenshots

![Presentation1](https://user-images.githubusercontent.com/77563792/199177480-0da12382-aafd-44e1-a206-b2d7fbdf873c.jpg)

![Capture](https://user-images.githubusercontent.com/77563792/199184181-e3ad90d8-b14f-44a9-b5ed-7dd4513ff5a1.JPG)

**Comment by cherylchan02** [comment]
hi i'm not very sure what this error means but I did encounter this error too. I think it might be the Num(Optional<T>). Num should always take in an Integer type so the Optional will also be Optional<Integer>. So instead of declaring a generic type T maybe just declare Optional<Integer> in the Num constructor?

**Comment by Penghao-99** [comment]
If I remembered correctly I added another private constructor and it removed some of the warnings. Not sure why this error occurs though. Would appreciate it if someone can shed some light on this.

**Comment by GarlicButterSteak** [comment]
Thanks for the responses guys! I haven started on the exercises but it turns out there's a trick to @SuppressWarnings("unchecked"), but I also don know what's the theory behind this hahaha

**Comment by bryanolm99** [comment]
Just listing out some guesses:
- did you extend Num from AbstractNum<Integer>? the problem might be caused by extending from AbstractNum<T>
- does your Num class a generic class (i.e. Num<T> ?) that might be redundant.

**Comment by wilsonwid** [comment]
> Thanks for the responses guys! I haven started on the exercises but in the fifth exercise it turns out there's a trick to @SuppressWarnings("unchecked"), but I also don know what's the theory behind this hahaha

I think Prof has disallowed usage of this method -- you're supposed to use another method that you've defined earlier to allow the return types to be `Maybe<R>`.

**Comment by GarlicButterSteak** [comment]
> hi i'm not very sure what this error means but I did encounter this error too. I think it might be the Num(Optional). Num should always take in an Integer type so the Optional will also be `Optional<Integer>`. So instead of declaring a generic type T maybe just declare `Optional<Integer>` in the Num constructor? One more thing to add, is your Num class extends from AbstractNum? I think you need to specify the generic type. So it should be `Num extends AbstractNum<Integer>`



> Just listing out some guesses:
> 
> * did you extend Num from `AbstractNum<Integer>`? the problem might be caused by extending from `AbstractNum<T>`
> * does your Num class a generic class (i.e. `Num<T>` ?) that might be redundant.

Thanks so much guys! CodeCrunch has finally accepted my files; while my outputs are wrong there's at least no warning when I changed to Num extend AbstractNum<Integer>. I was previously using Num extend AbstractNum<T>. But actually I still don't get whats going on here hahahaa my knowledge of generics is not pinned down like honestly I don even know why I shouldn't do Num<Integer> extends AbstractNum<Integer>, do yall happen to know which part of the slides talks about this or if you have any good resources I would be grateful as well 🙏

**Comment by bryanolm99** [comment]
> I don even know why I shouldn't do Num<Integer> extends AbstractNum

I think this is similar to our Project where we do `EventComparator implements Comparator<Event>`. We don't do `EventComparator<T> implements Comparator<T>` because we are confident that we are only dealing with Events here, so there's no need for generics. Similarly for Num, we know that we are only dealing with Integers, so we don't bother allowing Num to do generic typing.

**Comment by GarlicButterSteak** [comment]
> > I don even know why I shouldn't do Num extends AbstractNum
> 
> @GarlicButterSteak I think this is similar to our Project where we do `EventComparator implements Comparator<Event>`. We don't do `EventComparator<T> implements Comparator<T>` because we are confident that we are only dealing with Events here, so there's no need for generics. Similarly for Num, we know that we are only dealing with Integers, so we don't bother allowing Num to do generic typing.

Ahhh makes a lot of sense thanks!!
