### ISSUE TITLE
Jshell cannot find symbol 

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2030/2223-s1#248]
![image](https://user-images.githubusercontent.com/82555990/199207404-715fdf78-5ead-4781-84ac-cd87ad92afd9.png)

is there anyone who encountered the same problem before? My code worked fine when I was doing the first two levels.

**Comment by SungMatt** [comment]
There's likely some compilation error. Try do `javac Num.java` in the Terminal, outside of Jshell.

**Comment by ziyi105** [comment]
Oh it works now! thank you so much!
