### ISSUE TITLE
Lab 7 level 2

### ISSUE THREAD

**Issue by BlabbyDuck** [nus-cs2030/2223-s1#249]
# Summary

Unsure of how to approach this level aka the add function. I tried using Stream.iterate(...)..., but somehow I still can't obtain the answer. Any tips?

**Comment by rachelsitoh** [comment]
U can try using a for loop, might be easier, and break out of the loop once the value has been reached, else use succ()

**Comment by BlabbyDuck** [comment]
I solved it, thx!
