### ISSUE TITLE
[Exercise 5] Failed Test Case 5_1

### ISSUE THREAD

**Issue by nicholastxj** [nus-cs2030/2223-s1#251]
<img width="485" alt="Screenshot 2022-11-02 at 2 38 18 PM" src="https://user-images.githubusercontent.com/99980279/199417807-9a95d0ac-91d9-4468-ad43-298df8af1d8a.png">

Did anyone else encounter this error? I think it has something to do with my `or` method but can't really determine what it is; changing my current implementation just makes me fail an earlier test case related to the `or` method

**Comment by acekhoon** [comment]
That happens because your return type is not Maybe<A>, but Maybe<? extends A>. Fix your return type to Maybe<A> and don't use Maybe<? extends A> as the output type. That's why the error is raised.

**Comment by nicholastxj** [comment]
Yep after a little more digging I saw it, thanks!
