### ISSUE TITLE
Lab 7 Level 2

### ISSUE THREAD

**Issue by glendon29** [nus-cs2030/2223-s1#253]
Hi would appreciate tips in on how to do level 2. Currently thinking of using for loop but unable to retrieve the int value from the AbstractNum opt

**Comment by wjiayis** [comment]
Hi there,

I think a while loop is more apt than a for loop, since there isn't a readily accessible integer to serve as the ```n``` in the for loop (at least in my implementation). I had a ```while (n.isValid())``` loop and updated n every cycle.

**Comment by Tristanlimyr** [comment]
Hi, what I did was to initialise a counter = Num.zero(). So I will keep calling succ() on both counter and m until counter equals n.

**Comment by acekhoon** [comment]
Hello!

Actually you don't need to retrieve the int value from your optiinal. Rather, since optional is the one which handles the value inside the num instance, either you can loop the Num(0) it until it hits Num(n) value or reduce the value from n to zero and checking it by is.Valid() as mentioned above. I implemented the former one because it is simply easier to do.

**Comment by YEETTTTTTT** [comment]
you don't need to get the value, just check if they're equal

**Comment by mohddanesh** [comment]
like the abovementioned comments, I initialise a counter = Num.zero(). In while loop, call succ() on both counter and m until counter equals n.

**Comment by keefetok** [comment]
you can or can dont use a (while) loop.

i found out that doing a stream and reducing it works well with an additional method i made to check optional :)

**Comment by glendon29** [comment]
heyy @keefetok would you mind if you can share how you implement a stream for this use case

**Comment by giorgiocana** [comment]
Hi, this is the logic I followed:

Check if both this and the passed number are valid. If not then return an invalid number.
If both valid, initialise a counter zero(). Then construct while loop till counter and number optional are equal. The while loop updates both your number and the counter. Then return the obtained value.

Hope this helps!

**Comment by keefetok** [comment]
> heyy @keefetok would you mind if you can share how you implement a stream for this use case

hey @glendon29, giorgio has given an idea for how to to do a while loop construct and is actually very logical, try to maybe do it in the form of variables you are comfortable with, then subbing in with the question requirements.

Onto your question:

i generate a stream of <T> (depends on which part of the question i am on) using either iterate/generate <-- take note they have different inputs (iterate uses a seed, unaryoperator) while generate takes in a supplier.

From this, I make an optional of the stream type --> Optional<Stream<T>>. You should remember that optional.map can help in returning this but do take note which variable's optional you are using. Isit the parameter input? or isit this.

Then afterwards I just flatMap, map, reduce, apply <-- i dont use all, depends on whether it is mul,add,sub. 

Hope this helps!

**Comment by RezwanAhmed123** [comment]
I see alot of people using counters but I also realised you can do it just using the negative function provided.

Once you have checked if both numbers are valid, you can create two optionals opt1 (this opt) and opt2 (opt of the number to be added). Then, flip the optional of the second number to a negative value using the n function (opt2 becomes -x) and then create num2. Then use a while loop which keeps checking if num2 is valid and inside the loop itself you can increment both the opt of the first number and the negative opt by 1 using s and reassigning num2 to Num.of(opt2) and once opt2 becomes optional(0) the loop stops and opt 1 will be the opt of the number of the sum.
