### ISSUE TITLE
Lab 7 Level 4 

### ISSUE THREAD

**Issue by YEETTTTTTT** [nus-cs2030/2223-s1#254]
Hi, I am stuck on level 4, I'm not sure how to design my Fraction class. Currently I'm returning a Frac in the of method but i'm lost on how to write the private constructor. I was thinking of something like private Fraction(AbstractNum<Pair<Num, Num>> value), but I'm not sure if we're allowed to modify the abstractnum class. Can anyone tell me if i'm on the right track? Thank you

**Comment by zhanyi3** [comment]
I don't think we are allowed to modify what's given. Implementing `class Fraction` should be similar to `class Num` just that now instead of `class Num extends AbstractNum<Integer>` is will be `class Fraction extends AbstractNum<Frac>` the idea is the same. so your private constructor can be like `Fraction(Optional<Frac> opt)` and calling `super(...)` .

**Comment by mohddanesh** [comment]
i think you shouldn't return a Frac in of method. you should return a `new Fraction` by calling private constructor. Observe what the AbstractNum constructor is like.  You can actually pass` frac` type directly into AbstractNum's constructor. so you can something like `Fraction(Frac frac)` and call super() for one of the parent constructor

**Comment by acekhoon** [comment]
I was stucked for fair amount of time to think about where the fraction class should inherit from, and it should be AbstractNum<Frac> because your fraction is created based on frac class, and each frac instance is stored in optional<T> in abstractnum, so it should inherit from AbstractNum<Frac>.

**Comment by YEETTTTTTT** [comment]
Thanks everyone for the help, I've managed to come up with a working design. However, I'm stuck again on how to return just one NaN for invalid numbers. Currently, I'm returning NaN : NaN. Since we cannot use IfPresent or IsEmpty, I'm not sure how to check if any of the numbers are empty to return a single NaN

**Comment by zhanyi3** [comment]
you can use `isValid()` method from `AbstractNum` class to filter

**Comment by dohaduong** [comment]
@YEETTTTTTT i think a trick to use isEmpty for this lab is checking if it’s equals.(Optional.empty())

**Comment by dohaduong** [comment]
@YEETTTTTTT i think a trick to use isEmpty() for this lab is to check this.equals(Optional.empty())

**Comment by lanqinggg** [comment]
Hi! I used filter with isValid() on both Num produced so if they are not valid they will become empty optional, then I used .equals to check whether they are actually Optional.empty(). If so, it is invalid and I just return a Fraction with empty optional.

**Comment by liAiyujelly** [comment]
Hello! I used isValid() to check for both Num n & Num d in my of method and if anything is wrong I would just create a new Fraction with an empty opt.

**Comment by KEEWEIKUANG** [comment]
Ive made use of the "of" method in my Num class to change it to a Num, also ive made use of the "of" method in Frac class to convert it to a Frac. One of the private constructor in my Fraction class takes in a Frac and then just call super(...)

**Comment by glendon29** [comment]
How do we actually implement Optional together that happens to take in 2 int. Pretty confuse with the design structure regarding this

**Comment by bryanolm99** [comment]
@glendon29 you should use an `Optional<Frac>` as Zhan Yi has said above.

**Comment by glendon29** [comment]
@bryanolm99 for optional<Frac> im thinking it needs a optional.of() method which takes in the 2 int values. How would u also implement the static of method of

**Comment by bryanolm99** [comment]
@glendon29 Optional from java.util already implements `static <T> Optional<T> of(T value)`. So instead of passing 2 int values, you encapsulate them within a Frac, then pass this Frac to Optional's of() method.
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Optional.html

**Comment by mohddanesh** [comment]
@glendon29 Optional.of can only take a single variable. You can encapsualte 2 values in a single variable by using Pair class. In the qn, Frac is a subclass of Pair so you can let Frac take 2 variable and make the frac object an Optional

**Comment by YEETTTTTTT** [comment]
Thanks everyone for the help, it worked!
