### ISSUE TITLE
Missing a Javadoc comment

### ISSUE THREAD

**Issue by KeeveKang** [nus-cs2030/2223-s1#255]
# Summary

I did checkstyle on my code and i got the error "Missing a Javadoc comment. [MissingJavadocMethod]" for my Fraction class for the add, sub and mul methods. Tried moving the lines around and still got this error. Codecrunch also returns the same error. Not sure how to proceed on this :')

## Code Snippets
![codesnippet](https://user-images.githubusercontent.com/108913833/199549980-84374d75-fd32-403b-884f-c91229bf8d97.png)

## Screenshots
![image](https://user-images.githubusercontent.com/108913833/199550467-b5497b3e-9f84-45dd-825e-65a7474422be.png)

**Comment by dohaduong** [comment]
I think you can try update to jdk17, just try to run `sudo apt install openjdk-17-jdk openjdk-17-jre` in your command prompt

**Comment by yewey2** [comment]
Sometimes if you declare your function public, this will happen... Just remove public and it'll be fine!

**Comment by KeeveKang** [comment]
Hello! as yewey2 mentioned, removing public solved it :)
