### ISSUE TITLE
Lab 7 Level 1 How to convert to Optional<Integer>

### ISSUE THREAD

**Issue by giorgiocana** [nus-cs2030/2223-s1#256]
# Summary

Hi, I'm stuck at lab 7 level 1, second part. I keep getting a type conversion error because my this.ppt is of type T and the function AbstractNum.S takes in Integers. Any idea on how to solve the issue? 

## Screenshots

![image](https://user-images.githubusercontent.com/100380492/199571487-47b73cef-01d6-4104-86f2-f76e93e54ec7.jpeg)

**Comment by Y-ZR** [comment]
Hello, did you specify your Num to be of generic type Integer, such that it inherits from AbstractNum<Integer>

**Comment by giorgiocana** [comment]
Hi, thanks for the prompt response! 

Do you mean for the class type itself or for the method return type?

- My class is defined as Num<T> extends AbstractNum<T>
- My method returns Num<Integer>

**Comment by zclzz** [comment]
Hi i think what y-zr meant was if u specified the inherited class `AbstractNum` to be of type `Integer `. so `... extends AbstractNum<Integer>`

**Comment by giorgiocana** [comment]
So I should have something like  `Num<Integer> extends AbstractNum<Integer>`?

Isn't there a way to keep the generic type instead?

**Comment by zclzz** [comment]
Num is a class that does not take in a generic type. Whereas if u take a look at AbstractNum<T>, it does. So u would be doing `Num extends AbstractNum<Integer>`

**Comment by giorgiocana** [comment]
I see, thank you so much for the help!
