### ISSUE TITLE
Lab 7 Level 1. How to make Num.of(-1) ==> NaN?

### ISSUE THREAD

**Issue by joeyHXD** [nus-cs2030/2223-s1#260]
I am kinda stuck here. At lab 7 level 1
```
jshell> Num invalid = Num.of(-1)
invalid ==> NaN
```
In the task requirement it says:
![image](https://user-images.githubusercontent.com/68325229/199653080-2d4d5528-23ae-464c-83fd-f53f9dd33a46.png)
Does this mean that we cannot overwrite the toString method? According to the requirements?
```
public String toString() {
    return this.opt.map(x -> x.toString()).orElse("NaN");
}
```
Then how do I make this return NaN?

**Comment by wjiayis** [comment]
Hi Joey,

'NaN' is actually in the AbstractNum toString(). So actually in Num, you don't need to define any toString(), it'll work as expected.

Hope this helps!

**Comment by GarlicButterSteak** [comment]
Yeap I believe you can't override the toString() method. I believe that you just have to make use of the predicate AbstractNum.valid and the filter method of the Optional class in your Num constructor

**Comment by dohaduong** [comment]
I think for Num what you should do is check if the integer is valid in the of method and leave the NaN part to the given toString() in your AbstractNum

**Comment by joeyHXD** [comment]
> 
yes but i dont know how to make AbstractNum return NaN...

**Comment by joeyHXD** [comment]
as long as the T object contains toString, it will never return NaN right?

> yes but i dont know how to make AbstractNum return NaN...
> 
> I think for Num what you should do is check if the integer is valid in the of method and leave the NaN part to the given toString() in your AbstractNum

**Comment by joeyHXD** [comment]
can you give an example of a AbstractNum that would return NaN?

**Comment by wjiayis** [comment]
Hi Joey,

Num class extends AbstractNum<Integer>.

Hope it helps:)

**Comment by OngMinXian** [comment]
AbstractNum<Integer>(Optional.empty()) would result NaN when printed

**Comment by wilsonwid** [comment]
Preferably, you can also use Optional.empty() together woth the Num constructor.

**Comment by dohaduong** [comment]
@joeyHXD so basically I think for toString() in AbstractNum, it will return NaN if the optional inside AbstractNum is empty.
So what I did was just return a new Num(Optional.empty()) if the integer passed in is not valid

> as long as the T object contains toString, it will never return NaN right?
> 
> > yes but i dont know how to make AbstractNum return NaN...
> > I think for Num what you should do is check if the integer is valid in the of method and leave the NaN part to the given toString() in your AbstractNum

**Comment by joeyHXD** [comment]
Oh I didnt thought of that! thanks a lot guys!
