### ISSUE TITLE
Lab #7 Level 3

### ISSUE THREAD

**Issue by yqlok17** [nus-cs2030/2223-s1#264]
Not sure how to proceed with regards to completing Level 3 of Lab #7 for the subtract method.

Currently I've implemented helper methods to help me make the number negative such that for m.sub(n), I would be able to implement -n.sub(m) for Level 3, and an additional add method that does not check for the validity of the Num object before adding.

I'm not sure how I can possibly make the result of -n.sub(m) invalid if the result is < 0. Do I have to create an overloaded of() method which uses another constructor? Understand Optional.get() is banned for this lab. Any tips would be appreciated.

**Comment by dohaduong** [comment]
Hi so for this, my approach was filter the result.opt with the given super.valid, so it’ll just filter out the invalid and return the correct Optional - which may be empty or valid

**Comment by giorgiocana** [comment]
I'm having the same issue here. How do you use the valid method on the number contained inside the optional? I tried to use a map function, but I can't make it work without using `null`.

**Comment by keefetok** [comment]
> I'm having the same issue here. How do you use the valid method on the number contained inside the optional? I tried to use a map function, but I can't make it work without using `null`.

you don’t have to! you just have to check with the static Num of(Optional) method u can implement to help check validity of the number

**Comment by giorgiocana** [comment]
Yet again, how to create a static Num of(Optional) and checking the validity of the optional without getting the optional's value?

**Comment by keefetok** [comment]
> Yet again, how to create a static Num of(Optional) and checking the validity of the optional without getting the optional's value?

return a new Num(opt.filter(valid))

**Comment by yqlok17** [comment]
@dohaduong Thank you for the tip!

@giorgiocana There isn't actually a need to create a new constructor like static Num.of(Optional) come to think of it. You just need to make use of the given valid predicate and apply the filter method to get the desired comparison outcome.

**Comment by giorgiocana** [comment]
@keefetok That worked! Thanks. I completely forgot about the optional filter method.

**Comment by mohddanesh** [comment]
I use the same way to check for validity as  @keefetok using filter at return
