### ISSUE TITLE
[Excercise 5] How to do TypeCasting with Maybe

### ISSUE THREAD

**Issue by XihuaZ** [nus-cs2030/2223-s1#265]
I was trying to implement the method `or()` in Excercise 5 Level 5, where I tried typecasting. However, I got this error.

<img width="360" alt="Screenshot 2022-11-03 at 17 36 17" src="https://user-images.githubusercontent.com/91673283/199688165-eaa36f9a-2366-4583-946b-ccfdf053a219.png">

This is what my code looks like for `or()`:
```
    Maybe<T> or(Supplier<? extends Maybe<? extends T>> supply) {
        if (this.thing == null) {
            Maybe<T> a = supply<Maybe<T>>.get();
            return a;
        } else {
            ...
        }
    }
```

Anyone knows why I got this error?

**Comment by wilsonwid** [comment]
I don't think you can use typecasting for this particular question. A hint is that you should use a method that you've defined previously to convert it to a Maybe<R>
