### ISSUE TITLE
Ex5 level 3 Maybe

### ISSUE THREAD

**Issue by zclzz** [nus-cs2030/2223-s1#269]
Hi does anyone know how to go about implementing the filter method for maybe. Right now I can only thing of converting to `Optional `and filtering using the input predicate, but that does not work for the second filter

**Comment by OngMinXian** [comment]
You can use the predicate to filter the property this.thing directly.
So it will predicate.test(this.thing), then you just return appropriate Maybe object depending on the result of the predicate test

**Comment by zclzz** [comment]
> You can use the predicate to filter the property this.thing directly. So it will predicate.test(this.thing), then you just return appropriate Maybe object depending on the result of the predicate test

hi thank you for the prompt response! however it still does not work for the second filter? 
![image](https://user-images.githubusercontent.com/107348650/199796553-241c38a7-03e9-4205-9a17-2afe92c7dffb.png)

**Comment by wilsonwid** [comment]
I think you can see the error message and fix the error accordingly as it says that "... as a member of the raw type `Maybe`". Hope this helps!

**Comment by zclzz** [comment]
> does your `filter()` method return a `Maybe<T>`?

hi yes it returns a `Maybe.<T>of(this.thing)`
