### ISSUE TITLE
PA2 AbstractIntExpr cannot be modified?

### ISSUE THREAD

**Issue by yewey2** [nus-cs2030/2223-s1#270]
So I implemented subtraction, div etc... in AbstractIntExpr during PA, but when I check on codecrunch the AbstractIntExpr is resetted?

![image](https://user-images.githubusercontent.com/83965035/199969738-c879ae4d-f386-424c-9b82-60e624a76371.png)

Is this supposed to be a bug, or must we copy everything like subtraction and stuff into IntExpr?

I also implemented some overloaded constructors, they can't be accessed as well, any way around that?

**Comment by ShiJiaAo** [comment]
Does it work when you test it manually? perhaps also try AbstractIntExpr.subtraction instead if you implemented it as a static variable

**Comment by yewey2** [comment]
> Does it work when you test it manually? perhaps also try AbstractIntExpr.subtraction instead if you implemented it as a static variable

@ShiJiaAo yep it works when I test on my computer (and during PA), but when I submitted it again (cos something wasn't private final) it stopped working

**Comment by wishdbekuc** [comment]
i think we are supposed to define those functions in the IntExpr class instead!

**Comment by yewey2** [comment]
yeah, hopefully prof / the TAs can clarify, I overloaded some constructors and need them to work :")

**Comment by ShiJiaAo** [comment]
> i think we are supposed to define those functions in the IntExpr class instead!

Yeah I have a feeling this was intended.. I've noticed if we are provided classes we usually don't edit them.

But it's a bit weird from a design perspective. If add and multiply are in an AbstractIntExpr then why should the other 3 operations be defined somewhere else. Furthermore if an abstract int expression can do add and multiply then why should it not be able to do sub or divide etc.

Perhaps this is a subset of possible buggy test cases prof mentioned in his email

**Comment by yewey2** [comment]
lol wasn't that email just copy-pasted from PA1 hahaha, he didn't change PA1 to PA2

**Comment by Wenbo-J** [comment]
I heard from my TA that we cannot modify given classes, just gotta copy paste those over to our own class :')

**Comment by dohaduong** [comment]
My TA also confirmed before the PA that we cannot modify any given class
