### ISSUE TITLE
PA2 Level 3 Hints

### ISSUE THREAD

**Issue by yewey2** [nus-cs2030/2223-s1#273]
No idea how to go on, I've coded out everything from levels 1 to 5 but still stuck at level 3.

From level 3 hint...
> `Here's a hint... suppose the current expression is 2 + 3. If the next operator is an addition, say 2 + 3 + 4, then it could be first evaluated to 5 + 4. However, if the next operator is a multiplication, say 2 + 3 * 4, then we cannot evaluate 2 + 3 first; we need to evaluate the expression starting with 3 * 4 (and possibly anything after) to a value, and then perform the addition.`

The `(and possibly anything after)` seems to suggest that we need to somehow store the values in a stream or a list? How do we check for that?

**Comment by yewey2** [comment]
My current plan involves 
1. creating a pair class
2. init a Stream of Pair of (Optional.of(T) , Optional.of(operator))
3. each time new expr(T), stream add pair(optional(T), empty)
4. each time op(operator, t), stream add two pairs, 
first pair (empty, optional(operator))
second pair (optional (T), empty)
5. somehow compare the operators and reduce the stream by precedence

This seems overly complicated, any simpler way around this?

**Comment by ginloy** [comment]
One way is to think of an Expression is as a recursive Tree which has an operator and 2 Expressions
```
x * y + z =
          +
        *   z
      x   y

x + y * z =
           +
         x   *
           y   z
```

**Comment by yewey2** [comment]
Hmm interesting approach, I'll try it out. Thanks!

**Comment by yewey2** [comment]
![image](https://user-images.githubusercontent.com/83965035/200153081-f78fd836-df79-4892-b9dd-cfc1fd9c10d6.png)

I've tried implementing it as a tree, but I got this error... anyone facing the same issue?

**Comment by ginloy** [comment]
I had this also. There are likely logical errors when comparing precedences and building the tree.

**Comment by RezwanAhmed123** [comment]
Hi I was also trying to implement it as a tree but I get errors like this for the String test case, does anyone know why it could be?
![image](https://user-images.githubusercontent.com/95862073/200157518-6a27f817-af49-4fe0-9b8e-6a92f1b4a5ec.png)

**Comment by Ryan-loves-movies** [comment]
@yewey2 I'm also facing the same issue, although I do not have a solution, the problem lies in the fact that "2 + 3 * 4 ^ 5" is being evaluated as "2 + 12 ^ 5"

**Comment by yewey2** [comment]
> 

@Ryan-loves-movies I fixed it, the main issue is that op() is unnecessarily evaluating. You can try delegating the job of lower precedence operator to an evaluating function eval(), and higher precedence operator to op()

**Comment by yewey2** [comment]
not sure if might be the case, but are you evaluating the Expr multiple times?

I didn't face this error, but I presume it's testing for multiple evaluations of the same expression... might wanna wrap it in some sort of context manager instead of returning T directly?

**Comment by yewey2** [comment]
Since PA2 is over imma close this thread. Hope this thread helped and good luck for finals!
