### ISSUE TITLE
is final open or closed book?

### ISSUE THREAD

**Issue by mohddanesh** [nus-cs2030/2223-s1#274]
it was mentioned in the lecture that we do the final questions on our laptops. Can we only access hard copy notes? Can we use soft copy notes on our laptop? also, is screen recording needed? Despite having internet access, I assume we cannot use google right? But are we still allowed to open the JDK 17 page on google?

**Comment by kohlindy** [comment]
Yes please, can someone inform us if their TAs said anything or have any information? Thank you!

**Comment by Wenbo-J** [comment]
I remember hearing the TAs say it's openbook, but I'd also like to know about the details and the other questions

**Comment by wjiayis** [comment]
In case anyone missed the email, Prof mentioned it is open book:)

**Comment by giorgiocana** [comment]
Open book, you can also use the local files on your computer if I'm not wrong. Just don't google and/or contact anyone to get help.
