### ISSUE TITLE
Fail Test Case 5_2

### ISSUE THREAD

**Issue by izascia256** [nus-cs2030/2223-s1#275]
All my other test case has passed but I am still failing this test case. Anyone can help point out what is wrong?

![image](https://user-images.githubusercontent.com/112748524/200369008-a16b5aa1-3eeb-4269-a096-e1a302b0891b.png)

**Comment by wilsonwid** [comment]
You might want to check whether you lazily evaluate the entire expression or do some sort of half-evaluation when doing `.op()` with an `Expr<T>`. The former is the correct way to do it.
