### ISSUE TITLE
Failed testcase 5_2

### ISSUE THREAD

**Issue by limyeechern** [nus-cs2030/2223-s1#278]
# Summary
I failed this test case but I am not sure what this test case is about. Has anybody met with this issue and resolved it? Or does anybody understand what the test case is asking based on the output? Appreciate any form of help thank you very much!

## Screenshots (if any): 
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/66681646/200714282-2413da7c-e3f9-4379-942e-e3febc81570d.png">

**Comment by wilsonwid** [comment]
There may be multiple half-evaluations done by your `op()` method, hence the presence of the additional `+`s. The only way to prevent this is to make sure that the `op()` method does everything lazily (i.e., without evaluating in the middle).

**Comment by izascia256** [comment]
As @wilsonwid metioned, check for half evaluations. i.e. no terminal operations should be performed on any streams in your `op()` method.

**Comment by limyeechern** [comment]
I have realised my mistake and it is because I did not remove an additional .get() in the function that was left there during the PA. Closing thread
