### ISSUE TITLE
PA2 Level 2 types do not correspond

### ISSUE THREAD

**Issue by giorgiocana** [nus-cs2030/2223-s1#279]
# Description
Hi, I have been struggling with PA2 level 2. Particularly, I don't know how to apply the operator to function when calling the op method in Expr<T>. I tried to typecast two optional, but the results appear to be the same.

## Screenshots (if any): 
<img width="754" alt="Screenshot 2022-11-09 at 14 35 14" src="https://user-images.githubusercontent.com/100380492/200756834-f3e7dec8-c0eb-43ca-afba-d09cbedd8779.png">

**Comment by izascia256** [comment]
If you are doing something like:

`<T>` before your method calls similar to that in `Maybe.java`  in Exercise 5. Remove it.

Doing that overwrites the `<T>` generic variable to be method specific and removes its association from the `<T>` on the class level.

Basically the code identifies the `<T>` to be different things.

**Comment by giorgiocana** [comment]
Thank you, it worked. 

To summarise, for this level you must make sure that only your `static of` method has the <T> in front. All the other methods should not have that. Then just need to apply the operator onto the two T objects :)

**Comment by giorgiocana** [comment]
Thank you @izascia256 , it worked.

To summarise, for this level you must make sure that only your static of method has the in front. All the other methods should not have that. Then just need to apply the operator onto the two T objects :)
