### ISSUE TITLE
pow operator in codecrunch

### ISSUE THREAD

**Issue by Tsang-Kai** [nus-cs2030/2223-s1#283]
![Screenshot 2022-11-11 164645](https://user-images.githubusercontent.com/110796576/201302490-a6db7c0f-5b3d-4e52-8c59-0b2aea989d8d.png)

Im stuck at a test case in codecrunch which has a operator pow. from my understanding of exp, pow should have a precedence value of 2, the equations should be:
2 + 3 * 4 ^ 5 and 2 + 3 + 4 ^ 5 where 4 ^ 5 is evaluated first, giving 3074 and 1029.
can someone explain this issue and how to solve it?

**Comment by wjiayis** [comment]
Hi there,

Given the ellipsis at the start of lines 80 and 83, there may be more chaining in front of what is shown. Perhaps you could check if your code allows for multiple ```.op()``` to be chained as intended.

Hope it helps!

**Comment by bransometan** [comment]
I have this error too and realised that my exp function is defined incorrectly. Maybe you can check on your exp function definition.

**Comment by keefetok** [comment]
hi, i had same problem as you where my code was doing 2 + 3 * 4 ^ 5  instead of 2 + (3*4)^5

one thing i relooked at was my overloaded constructor and see whether my Expr was returning an evaluated & updated version instead

**Comment by Tsang-Kai** [comment]
i overlooked that in level 5 u have to evaluate the expr in the bracket first. thanks for the comments.
