### ISSUE TITLE
Error from PA2 Submission

### ISSUE THREAD

**Issue by acekhoon** [nus-cs2030/2223-s1#284]
# Summary
Put a summary of the problem here

## Description 
Hello! My code got stucked in test case 9 where my code print one more plus? sign which is not identical to the expected output. Does anyone know why this error occurs?

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
<img width="1408" alt="Screenshot 2022-11-11 at 7 25 00 PM" src="https://user-images.githubusercontent.com/109423589/201330839-770e51d9-d9c6-429a-b1ed-db19a6ffd9a6.png">

**Comment by izascia256** [comment]
Check for half-evaluations. Everything must be evaluated lazily until it is called upon in your `toString()` method. No other forms of evaluation will be allowed.

**Comment by acekhoon** [comment]
Aight resolved this issue. Thanks!
