### ISSUE TITLE
Lab 8 Self-Check priority

### ISSUE THREAD

**Issue by eLTehh** [nus-cs2030/2223-s1#286]
Any particular priority for the self-check counters? Stuck at this test case
![image](https://user-images.githubusercontent.com/48056361/201459019-6966126d-0ba8-4620-8afb-c3e8924b02dd.png)

**Comment by izascia256** [comment]
Typically, the customer with the lower number is always served first because they arrived first. Did your customer 12 just vanished from your code?

**Comment by RezwanAhmed123** [comment]
It’s most likely your done event not being triggered properly. Did you miss out any cases where the customer gets removed but a done event is not created?

**Comment by yewey2** [comment]
Might be an implementation of your queue... Did you update your self check server's queue to a new ImList<Customer>(customer)?

**Comment by eLTehh** [comment]
Solved it. Basically each self check counter was acting as its own individual queue instead of a shared queue.
When customers were waiting, they didn't check for whether another counter was available. Just made sure to include this check and it passed
