### ISSUE TITLE
Ex 5 Maybe

### ISSUE THREAD

**Issue by zclzz** [nus-cs2030/2223-s1#294]
Hello, does anyone know why is the test case here true? Shouldn't the equals method return true when "_the contained values are "equal to" each other via their respective equals method._" In this case `new A(1).equals(new B(1))` is true?

![image](https://user-images.githubusercontent.com/107348650/202901689-5c024ec4-d38b-4425-8a81-eae9f544bc47.png)

**Comment by wjiayis** [comment]
I think there is some form of inheritance relationship between A and B, making A and B substitutable, and thus ```ma.equals(mb)``` returns ```true``` . You could check if your main if statement uses ```Maybe<?>``` rather than ```Maybe<T>```, as that clause is supposed to check the ```.thing``` attribute as long as ```other``` is a ```Maybe```.

**Comment by junhuiii** [comment]
Agree with @wjiayis's comment, if you did a `else if obj instanceof Maybe<T>` then it wouldn't enter the clause and thus return `false`.

**Comment by zclzz** [comment]
> I think there is some form of inheritance relationship between A and B, making A and B substitutable, and thus `ma.equals(mb)` returns `true` . You could check if your main if statement uses `Maybe<?>` rather than `Maybe<T>`, as that clause is supposed to check the `.thing` attribute as long as `other` is a `Maybe`.

Hi thanks for the reply! I already did a `Maybe<?>` typecast. However I did try to include a `maybe.thing.equals(this.thing) `statement. This throws an error whenever a `Maybe.empty() `is compared. How do you check for the fact that `other.thing` has an inheritable relationship with `this.thing`

**Comment by wjiayis** [comment]
Hi, to compare between ```Maybe.empty()```, you would need to do a check to see if ```this.thing``` is ```null```. If it is, then you check if the other thing is null as well. Your current error is thrown because null does not have a ```.equals()``` method iirc.

**Comment by jamielfh** [comment]
Agreed with @wjiayis above, I personally used if-else clauses to account for the cases where both things are null and where both things are not null.

**Comment by zclzz** [comment]
yep managed to find the bug! thanks guys!
