### ISSUE TITLE
Exercise #5: Maybe Level 6

### ISSUE THREAD

**Issue by anniedaang** [nus-cs2030/2223-s1#295]
I have issues casting the return type of my flatMap function so that I can assign it later on to another Maybe object.
I've tried different variations but haven't succeeded. Can someone provide some insights and guidance?

**Here's my code:**
<img width="556" alt="Skärmavbild 2022-11-21 kl  11 57 52" src="https://user-images.githubusercontent.com/71130637/202962531-939a762a-19e3-4031-ba17-25a56d73da5d.png">

**The error:**
<img width="571" alt="Skärmavbild 2022-11-21 kl  11 58 03" src="https://user-images.githubusercontent.com/71130637/202962554-e11a97f9-cd0b-453b-b3f1-6435a05aa4de.png">

**My other approach was this:**
<img width="634" alt="Skärmavbild 2022-11-21 kl  11 59 30" src="https://user-images.githubusercontent.com/71130637/202962696-c94baf8e-bb9e-47e3-9081-fe9828859234.png">

**but then I get this error message:**
<img width="568" alt="Skärmavbild 2022-11-21 kl  12 00 02" src="https://user-images.githubusercontent.com/71130637/202962751-bb2f713a-c302-4bc7-b5e8-3f50be95bbfc.png">

**Comment by jamielfh** [comment]
Hi, my guess is you have to supply an upper-bound wildcard to Maybe, so it's <? extends Maybe<? extends R>>. Not exactly sure why it's as such (perhaps someone can explain below), but I would think it's similar to how Integer is a subtype of Number but List<Integer> is not a subtype of List<Number>.

**Comment by anniedaang** [comment]
> Hi, my guess is you have to supply an upper-bound wildcard to Maybe, so it's <? extends Maybe<? extends R>>. Not exactly sure why it's as such (perhaps someone can explain below), but I would think it's similar to how Integer is a subtype of Number but List< Integer > is not a subtype of List< Number >.

Yes it was an upper-bounded wildcard. Thank you for explaining! I fixed it now.
