### ISSUE TITLE
Lab 8 TLE test case 27

### ISSUE THREAD

**Issue by zclzz** [nus-cs2030/2223-s1#296]
# Summary
Hello does anyone know what test case 27 is and the reason for this TLE. My code managed to pass all the other TC except this one

## Description 
Test Case 9_16
## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/107348650/202976035-037c2f0b-9242-4426-bed4-d46ec432b299.png)

**Comment by wjiayis** [comment]
Hi there, looks like your simulate() method ran into an infinite loop. Perhaps if your implementation involves re-enqueuing certain customers, ensure that the code logic dequeues everyone eventually.

**Comment by zclzz** [comment]
> Hi there, looks like your simulate() method ran into an infinite loop. Perhaps if your implementation involves re-enqueuing certain customers, ensure that the code logic dequeues everyone eventually.

Hello thank you for the prompt response! yep my logic involves re-adding events back into the PQ, and I have ensured that unused events are polled out. Or rather, are there any suggestions that I could use to see if I have any more events in my PQ, particularly for this test case?

**Comment by giorgiocana** [comment]
The way I solved a similar problem is by printing all my queues and seeing which one repeated infinitely :)

**Comment by zclzz** [comment]
> The way I solved a similar problem is by printing all my queues and seeing which one repeated infinitely :)

hi but wont that fail other test cases that you have previously passed on code crunch

**Comment by zclzz** [comment]
okay solved the bug! thanks for the input everyone
