### ISSUE TITLE
Exercise 2 Compilation Error

### ISSUE THREAD

**Issue by limeunchan** [nus-cs2030/2223-s1#30]
Does anyone know what this error message means? 
```
BigCruise.java:7: error: variable cruiseLength might not have been initialized
    }
    ^
1 error
```
I definitely checked for the closing of brackets, and initialisation of the `cruiseLength` variable.. It also seems to run fine on my local machine

**Comment by SungMatt** [comment]
Was your initialization in some sort of conditional statement?

**Comment by limeunchan** [comment]
It was not
