### ISSUE TITLE
Recitation 7 3c, generic abstract class Func<T,R>

### ISSUE THREAD

**Issue by KEEWEIKUANG** [nus-cs2030/2223-s1#306]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/98325942/203921831-8c37d02c-1466-4a14-83ed-1ac119f919a0.png">

Hello, im rather confused with the generics above, like putting the appropriate alphabets in <>. Anybody can explain the flow of putting the correct alphabet? Thank you so much!!

**Comment by JuliaPoo** [comment]
Hi, could you specify where in the code you are asking about?

**Comment by KEEWEIKUANG** [comment]
> E.g., are you asking about the type of the argument of the method header `compose`, the format of the method header `compose`, etc?

 From the line 1 and line 3 of the codes, why is there a change of generic type from <T,R> to <U,R>?

**Comment by JuliaPoo** [comment]
Suppose you have a function `f` that converts a `Double` to an `Int` and then `g` that converts an `Int` into a `String`. We can do `gf = g.compose(f)` which in math notation will look something like: `gf.apply(x) <==> g.compose(f).apply(x) <==> g(f(x))`. In this sense, `.compose` is kinda like "prepending" an operation to a current one. Now `gf` converts a `Double` into a `String`.

```
        f       g
Double --> Int --> String
       ---------->
           gf

f has type Func<Double, Int>
g has type Func<Int, String>
gf has type Func<Double, String>
```

So when you are implementing `Func.compose`, you need to take into account that the final composed function could have a new "initial" type.

For this example above, the `f.compose(g)` would have the type matching as follows:

```
U: Double // The new "initial" type
T: Int // The type of the output of f and the input of g
R: String // The type of the output of g
```

**Comment by KEEWEIKUANG** [comment]
okie thanks all!
