### ISSUE TITLE
Administrative Question: Compulsory to Redo Exercises 1, 2, 4?

### ISSUE THREAD

**Issue by GarlicButterSteak** [nus-cs2030/2223-s1#308]
Hi just a quick question as per the title, just wondering if there will be a second set of compulsory re-grading for Exercises 1, 2, and 4 and whether we must therefore re-submit to CodeCrunch the re-done "streamified" code. Thanks in advance!

**Comment by ziyi105** [comment]
it's no compulsory

**Comment by wjiayis** [comment]
Hi there, the grades for Exercises 1, 2 and 4 have already been keyed into Luminus (you can check them in your grade book). You can resubmit your code to test against the new test cases but you will not be penalised if you choose not to do so.

**Comment by mersoncheong** [comment]
nope

**Comment by dohaduong** [comment]
nope your grade is already recorded before releasing the stream exercise

**Comment by acekhoon** [comment]
nope!

**Comment by GarlicButterSteak** [comment]
Thank you all 🙏
