### ISSUE TITLE
Error encountered while running test case on CodeCrunch

### ISSUE THREAD

**Issue by glendon29** [nus-cs2030/2223-s1#311]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/29744561/204088289-be979cac-2ee6-4bda-bf20-eb5a3e23d938.png">

Hi wanna ask if anyone encountered similar error to this. Cant seem to figure out on my side. Manage to pass the test case given by the lab

**Comment by bryanolm99** [comment]
hi! what are you trying to get from the ImList in the simulate() method? maybe that'll point you somewhere!

**Comment by glendon29** [comment]
hi! manage to pass the code was careless on my side did not catch the error the use case whereby there are no self checkout counters
