### ISSUE TITLE
Password for AY21/22 S2 final.zip

### ISSUE THREAD

**Issue by qwqdrz** [nus-cs2030/2223-s1#316]
Sorry I know it is a stupid question but I really cannot find where the password for the zip is. Can anyone find it?

**Comment by ziyi105** [comment]
![image](https://user-images.githubusercontent.com/82555990/204125241-3b772f13-ffc0-4bdb-85ea-aec65ba80d63.png)

**Comment by qwqdrz** [comment]
@ziyi105 Thanks!
