### ISSUE TITLE
Exercise 6 Task 1

### ISSUE THREAD

**Issue by glendon29** [nus-cs2030/2223-s1#323]
I have been stuck on how to filter Intstream in order to get the twin prime value ? any tips from people who have completed it thanks

**Comment by GarlicButterSteak** [comment]
Hello! Here's what I did, maybe you can give it a shot and try to fill in the blanks first, and check back in if more help is needed:

return IntStream.rangeClosed(...)
        .filter(......) // check if each number in the range is prime
        .filter(......) // check if the [before - 2/after + 2] number is prime and also that they are respectively within range

**Comment by SungMatt** [comment]
Alternative method:

in the function that is inside filter, you can check if the current number, and (the number + 2 is prime, or the number -2 is prime)

**Comment by dohaduong** [comment]
i think you can start with writing a intpredicate that checks if the number is a prime or not using intstream.iterate(...), where the intstream just basically checks if n % x != 0 (n = your input number, x = basically anything < n).

**Comment by glendon29** [comment]
Hi @GarlicButterSteak manage to filter through prime numbers but tried various methods but still unable to get the method to filter the adjacent number difference = 2

**Comment by GarlicButterSteak** [comment]
Hey! I think that if you managed to filter through the primes, I'm assuming you have a boolean isPrime method, and so all you need to do is pass in again, for instance, the predicate \x -> isPrime(x + 2)

**Comment by glendon29** [comment]
Thanks finally solve it. Thanks for all the help
