### ISSUE TITLE
Exercise 6 Level 3

### ISSUE THREAD

**Issue by glendon29** [nus-cs2030/2223-s1#325]
Hi for those who have completed how did yall manage to pass it. I used boxList and filter through the list but was met with an error due to index issue. Is there any other ways that yall solve this level ?

**Comment by bryanolm99** [comment]
i counted repeats using a sliding window, each time checking the (i)th, (i+1)th, and (i+2)th positions. increment the occurence if the i(th) and (i+1)th positions are the same and the (i+2)th position is different from the previous 2.

**Comment by YEETTTTTTT** [comment]
I used intstream.range(0, list.size()) to mimic the indexing of a list

**Comment by mohddanesh** [comment]
I use the same method as @YEETTTTTTT so I have a stream of index and access the list elements by using list.get(i) where i is the stream elements

**Comment by namsengi11** [comment]
I used intstream to index through the list, as well as a filter to check elements before and after to check if it is the "end of repeated digits"

**Comment by cherylchan02** [comment]
I also used intsteam to index through the list, then i used filter with a separated method that I created to check for repeated elements

**Comment by glendon29** [comment]
thanks guys manage to solve it
