### ISSUE TITLE
Exercise #3: off by 0.0000000000002

### ISSUE THREAD

**Issue by wjiayis** [nus-cs2030/2223-s1#33]
Hi there,

I kept getting this answer despite attempts to circumvent the floating point error. May I know if anyone has encountered the same issue?

Thanks in advance!

<img width="994" alt="Screenshot 2022-09-04 at 3 28 35 PM" src="https://user-images.githubusercontent.com/95198512/188302531-202afe04-517f-48d9-8e65-59fc9902ab5c.png">

**Comment by wilsonwid** [comment]
Hi, you might want to try defining the volume for `Sphere` in a _slightly_ longer way!

**Comment by wjiayis** [comment]
Oh I got it, didn't know multiplying the 4/3 at the start vs at the back makes a difference haha. Thanks a lot!

**Comment by axmszr** [comment]
> Oh I got it, didn't know multiplying the 4/3 at the start vs at the back makes a difference haha. Thanks a lot!

Thank you! This worked for me too.
