### ISSUE TITLE
Java Generics

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2030/2223-s1#331]
![image](https://user-images.githubusercontent.com/82555990/204335519-0c70f677-ca04-4631-838f-9357b0779ffe.png)

The Optional.empty() in of method will return an Optional<object>, which is then pass to the argument of type Optional<Expr<T>>

I dont understand why Optional<object> can be substituted by Optional<Expr<T>>

**Comment by bryanolm99** [comment]
I believe the first `Optional.empty()` is type-inferred to be equivalent to `Optional.<Expr<T>>empty()` and the second `Optional.empty()` is type-inferred to be equivalent to `Optinal.<Operator<T>>empty()`.

**Comment by ziyi105** [comment]
ohhh i see, thanks!
