### ISSUE TITLE
Exercise 6 Task 4 Game Of Life

### ISSUE THREAD

**Issue by glendon29** [nus-cs2030/2223-s1#335]
Hi guys been thinking of how to implement this but cant get the desired output. For those who have complemeted , any tips or guidance u can provide me on how and what to construct in the 2 methods

**Comment by junhuiii** [comment]
You will need a few `if_else` checks as you are doing the mapping for the generateRule() function. The number really depends on your implementation, but if you are really stuck, you can essentially find the full answer in Prof Chia's PYP review for `AY21/22S1 CS2030/S Final Assessment Review`.

**Comment by SungMatt** [comment]
For the second method, you can check out the comment I've written [here](https://github.com/nus-cs2030/2223-s1/issues/247#issuecomment-1328321412).

**Comment by glendon29** [comment]
thanks guys solved it le finally
