### ISSUE TITLE
for final: which jdk can we access?

### ISSUE THREAD

**Issue by mohddanesh** [nus-cs2030/2223-s1#339]
Hi! Does anyone have the link to the jdk doc we use for PA?

**Comment by GarlicButterSteak** [comment]
You can access it here: https://docs.oracle.com/en/java/javase/17/docs/api/ or under Module Details > Weblinks in Luminus!

**Comment by KEEWEIKUANG** [comment]
yup jdk 17 is the one we used for PA

**Comment by mohddanesh** [comment]
thank you everyone!
