### ISSUE TITLE
Exercise 3 floating point precision

### ISSUE THREAD

**Issue by zhanyi3** [nus-cs2030/2223-s1#35]
Hi, does anyone know what is the reason for this discrepancy? my `volume()` method for solid sphere I used the formula `(4.0 / 3.0) * Math.PI * Math.pow(radius, 3)` in a single line then `volume() * density` for `mass()` method
<img width="776" alt="Screenshot 2022-09-05 at 10 16 22 AM" src="https://user-images.githubusercontent.com/105008161/188348232-2a6c1d0c-7f69-4060-9366-23759192c4d1.png">

**Comment by timotius-jason** [comment]
Hi,

Perhaps you can try writing the formula for your volume() method in a different way.

**Comment by danqiye1** [comment]
> Hi, does anyone know what is the reason for this discrepancy? my `mass()` method for solid sphere I used the formula `(4.0 / 3.0) * Math.PI * Math.pow(radius, 3)` in a single line <img alt="Screenshot 2022-09-05 at 10 16 22 AM" width="776" src="https://user-images.githubusercontent.com/105008161/188348232-2a6c1d0c-7f69-4060-9366-23759192c4d1.png">

Hi can you provide me with a submission id so that I can take a look? You can find the submission id on codecrunch on your submission page for this error.

**Comment by zhanyi3** [comment]
2352911

> Hi can you provide me with a submission id so that I can take a look? You can find the submission id on codecrunch on your submission page for this error.

Submission ID: | 2352911
-- | --



Submission ID: | 2352911
-- | --

**Comment by bransometan** [comment]
I think maybe you can try using multiplication instead (e.g a x a x a instead of Math.pow(a, 3)) to see if the precision error still persist.

**Comment by bryanolm99** [comment]
> I think maybe you can try using multiplication instead (e.g a x a x a instead of Math.pow(a, 3)) to see if the precision error still persist.

Had the same precision error and was resolved using explicit multiplication.

**Comment by zhanyi3** [comment]
> > I think maybe you can try using multiplication instead (e.g a x a x a instead of Math.pow(a, 3)) to see if the precision error still persist.
> 
> Had the same precision error and was resolved using explicit multiplication.

I see! Thanks! Managed to solve the issue.

**Comment by wilsonwid** [comment]
Linking issue #33 to this issue as it may help some people!

**Comment by danqiye1** [comment]
> 2352911
> 
> > Hi can you provide me with a submission id so that I can take a look? You can find the submission id on codecrunch on your submission page for this error.
> 
> Submission ID:	2352911

Sorry I just saw this. But seems like this is resolved.
