### ISSUE TITLE
Anyone faced issue with restricted API being java.util.Objects

### ISSUE THREAD

**Issue by zccccclin** [nus-cs2030/2223-s1#40]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/60165401/188601424-e027642c-4710-47b9-b9e0-2e8aeece155b.png">
I have been facing this issue in both exercise 2 and 3, where it mentioned that restricted API objects is used. But after checking the API, I have confirmed that none of the methods in Objects is being used in my code.

Anyone faced a similar issue? Or have resolved it before?

**Comment by liewyungjun** [comment]
Hi I got this error from declaring and instantiating an attribute in one of my classes. I think the grading wants constants to be declared as private static final instead of private final

**Comment by danqiye1** [comment]
Hi, this could be due to a number of reasons. Better to let us have your submission id to take a look.
