### ISSUE TITLE
Get error I use getKey() and getValue method for Pair class object

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2030/2223-s1#45]
I am trying to return a pair of event and customer and assign them to other variables. However, i get a cannot find symbol error for getKey() and getValue() method. How can I resolve that? 

my code is as follow: 
Pair<Event, Server> pair = new Pair<Event, Server>(new LeaveEvent(this.customer), server);
Event event = pair.getKey();
Server server = pair.getValue();

**Comment by hongming321** [comment]
I think that is because the Pair.java file we were given does not contain getKey() and getValue() methods. Instead, it has only first() and second() methods.

**Comment by quek-zhiheng** [comment]
Hello! Not sure if you are referring to the Pair class for Lab 3, but the specific Pair class used in Lab 3 requires the use of `first()` and `second()` methods to get the first and second element of the Pair class respectively!

**Comment by kohlindy** [comment]
As mentioned above, you can try changing pair.getKey() to pair.first() and pair.getValue() to pair.second()

**Comment by ziyi105** [comment]
oh youre right! It works now, thank you so much
