### ISSUE TITLE
Lab03 output 

### ISSUE THREAD

**Issue by zhanyi3** [nus-cs2030/2223-s1#47]
Hi, does anybody know how do I prioritise customers who arrived first in my comparator? 
Currently this is my output

<img width="333" alt="Screenshot 2022-09-10 at 5 06 56 PM" src="https://user-images.githubusercontent.com/105008161/189476946-cdc14ce6-4083-43aa-bf30-08274c541a30.png">

**Comment by SungMatt** [comment]
The Comparator works for Events -- it can prioritize certain types of Events by returning either a positive or negative number, depending on which is more important.

**Comment by Wenbo-J** [comment]
For me, I subtracted 0.01 for DoneEvents ----- not the best way I'm sure, but it worked

**Comment by zhanyi3** [comment]
I see, thanks!
