### ISSUE TITLE
instanceof detected while no instanceof was used

### ISSUE THREAD

**Issue by Wenbo-J** [nus-cs2030/2223-s1#48]
# Summary

CodeCrunch is telling me that it detected instanceof, but I don't have a single instanceof in my code. Has anybody else also encountered this issue? 

## Screenshots
<img width="499" alt="image" src="https://user-images.githubusercontent.com/88523392/189477321-cd5f6181-0be9-4908-a005-00171fdb8a6f.png">

**Comment by wjiayis** [comment]
Hi Wenbo,

Perhaps your code was doing something equivalent to ```instanceof```. I think in general we should stay away from reflection. In my submission I used an ```int priority``` as tiebreaker between the classes, and I didn't receive the error. Perhaps you could try something similar:)

**Comment by danqiye1** [comment]
Hi @Wenbo-J, I will need your submission id to investigate further.

**Comment by Wenbo-J** [comment]
> Hi @Wenbo-J, I will need your submission id to investigate further.

It turns out that one of my comments had the word "instanceof" in it loll
