### ISSUE TITLE
[Lab] Persistence in vim/nano user preference files

### ISSUE THREAD

**Issue by SungMatt** [nus-cs2030/2223-s1#53]
Every week in the lab, I have to find myself re-importing the ~/.nanorc configuration file prior to starting. Do these configuration files get overwritten every lab? Is there some way of ensuring persistence between weeks?

**Comment by danqiye1** [comment]
Sorry, but the pe nodes are cleared every week. By default there should be a .vimrc file with the correct coding style in the nodes so I think using vim will be better.

**Comment by SungMatt** [comment]
That's a big oof. #NANOMASTERRACE!
