### ISSUE TITLE
Approach to Exercise 4 Level 1

### ISSUE THREAD

**Issue by XihuaZ** [nus-cs2030/2223-s1#56]
Am I supposed to just make use of a loop to modify the output of the toString method? Or am I supposed to make use of the Collector class to modify the String?

**Comment by chiralcentre** [comment]
Personally I used a for loop to add to the output string in the toString method

**Comment by OngMinXian** [comment]
I too used for loops to generate the output string. I added \n to create new lines when needed. Be careful not to add a space at the end of each line as that will be considered as not passing the test cases.

**Comment by Wenbo-J** [comment]
I used ImLists and kinda created a data structure that stores the input in a 2D matrix, then simply printed out the matrix in my toString according to the desired format

**Comment by bransometan** [comment]
I think you can use a loop to get your desired output for toString() method. For me, I created a String variable s, and just iterate through each element that is passed in the list and add the desired specifications (e.g "{" or ";") to that s. Then, I return s at the end of the toString() method.
