### ISSUE TITLE
Lab 3 Use of restricted API detected 

### ISSUE THREAD

**Issue by BlabbyDuck** [nus-cs2030/2223-s1#57]
# Summary

I have been experiencing this issue and have no idea how to solve it. Do anyone have any idea what resulted in this?
I am able to get the output correctly tou.. :')

![Screenshot 2022-09-11 at 9 24 21 PM](https://user-images.githubusercontent.com/108108396/189529983-1fb75355-aac3-4103-8759-159880787f11.png)

**Comment by XihuaZ** [comment]
I assume u made use of getClass() for Lab 3. It is not allowed as is the same for instanceof.

**Comment by danqiye1** [comment]
Hi, can I have your submission id to check on this?

**Comment by BlabbyDuck** [comment]
Yup, its 2361350

> Hi, can I have your submission id to check on this?
