### ISSUE TITLE
Use of Java reflection detected code check error

### ISSUE THREAD

**Issue by Kvnyu** [nus-cs2030/2223-s1#58]
# Summary
I am getting
 ```
Use of Java reflection detected.
Grading terminated.
```
When submitting my code

What could be causing this? I have no usage of `instanceof`. I am however using `Java.Util.Optional`. Could this be the cause?

**Comment by danqiye1** [comment]
Hi, can I ask for your submission id to check on this?

**Comment by xuan-jun** [comment]
Hello, I got this error too because I made use of the `getClass()` method defined under the `java.lang.reflect` which checks for the class of the object. Not sure if you have used this method but removing this method call solved the issue for me :)

**Comment by Kvnyu** [comment]
> Hi, can I ask for your submission id to check on this?

The id is 2361420

**Comment by Kvnyu** [comment]
> Hello, I got this error too because I made use of the `getClass()` method defined under the `java.lang.reflect` which checks for the class of the object. Not sure if you have used this method but removing this method call solved the issue for me :)

hmm, don't think I use that method but thank you for the reply!

**Comment by danqiye1** [comment]
@Kvnyu, use of enum is not allowed. I think it was mentioned in lecture yesterday.

**Comment by Kvnyu** [comment]
> @Kvnyu, use of enum is not allowed. I think it was mentioned in lecture yesterday.

Got it, thanks for the answer!
