### ISSUE TITLE
Exercise 3: Private access in Cuboid class

### ISSUE THREAD

**Issue by jingyiiiiz** [nus-cs2030/2223-s1#59]
I'm having troubles with declaring variables for Cuboids in task 2.

If the variables (height, length, width) are declared as private, this error comes out:
```
SolidCuboid.java:12: error: height has private access in Cuboid
               this.height, this.width, this.length, this.mass());
                   ^
SolidCuboid.java:12: error: width has private access in Cuboid
               this.height, this.width, this.length, this.mass());
                                ^
SolidCuboid.java:12: error: length has private access in Cuboid
               this.height, this.width, this.length, this.mass());
```

If I declare them as protected instead, there's another error message:
```
field height in class Cuboid
field length in class Cuboid
field width in class Cuboid
not declared private final
Grading terminated.
```

May I ask what should I do with these variables? Thanks in advance :))

**Comment by OngMinXian** [comment]
What I did was use something like 
a public getHeight method to access the properties. 
Not entirely sure this is allowed since Professor talked about getters in lecture.
But it seems like it is a must to retrieve the attributes using a getter

**Comment by bryanolm99** [comment]
Maybe you design is that `SolidCuboid` **has a** `Cuboid`, so you had problems when you wanted to access the properties (height, length, width) of `Cuboid`. Consider implementing the relationship where `SolidCuboid` **is a** `Cuboid`. That way you won't have issues accessing private variables in `Cuboid`.

**Comment by keefetok** [comment]
i did a get property method to get my variables rather than using this.

**Comment by keefetok** [comment]
its the design spec to do private final, but if you need a parameter, getters are always available.

so for example: radius --> getRadius
