### ISSUE TITLE
Exercise 4 Puzzle class

### ISSUE THREAD

**Issue by zandratay** [nus-cs2030/2223-s1#60]
"Define a constructor Puzzle(int n) that takes in a integer value n and creates a (n^2 − 1) puzzle in a solution configuration."

My Puzzle class will take in 2 parameters, a Grid2D<E> and an integer, n.  but they want to create the  (n^2 − 1) puzzle in a **solution configuration**. Are we supposed to use a loop to do so? are loops even allowed in constructors?

**Comment by ZhuLeYao** [comment]
Hi, I am wondering the same thing, do you have the answer to this?
