### ISSUE TITLE
Lab 03: Design Specification Error

### ISSUE THREAD

**Issue by GarlicButterSteak** [nus-cs2030/2223-s1#61]
# Summary

Design Specification Error

## Description:

Hello! I am still working through Lab 03 and encountered something. Now, I still don't really understand what a Priority Queue or Comparator is, but I was just submitting stuff into CodeCrunch _for fun_ and obtained the "Design Specification Error" when I submitted all the Java files I had. However, when I removed the Event Comparator class that implements Comparator<Event> and submitted the other remaining files, the error disappeared, and there was the usual output telling me that I did not pass the test cases (that is, the submission was still accepted unlike the submission including the Comparator class).

I am just curious about what is going wrong here and what I should be doing instead as I was under the impression that a Comparator class was required for this lab submission. Thank you in advance!

**Comment by OngMinXian** [comment]
I think you do need a class that implements Comparator. There is an example in the lecture slides that you can follow. Not sure why it says Design Specification Error but maybe you can get the correct output first before submitting.

As for what a Priority Queue is, you can think of it as queue but every element in the queue has some priority value to it. And elements with higher prority value will be taken out first. In this case, you would want to take out events that have a lower time first. But if two or more events have the same time, you would want to put events with the customers that arrived first as higher priority (comes out first). 

A PQ class is provided which you can use as your priority queue. The PQ takes in a class that implements Comparator. This class would then have your logic to determine which event has a higher priority.

Hope I explained it well and correct!

**Comment by nixonwidjaja** [comment]
I also got a Design Specification Error, and it because I did check instanceof or check class type. Perhaps if you do similar things like this, it will trigger the error. And yes, you need a class that implements Comparator.

**Comment by bransometan** [comment]
I think the design specification error is due to lack of comparator class. You need to include a comparator class and make use of it in your submission. As for the understanding of priority queue and comparator, I felt that the examples and visuals in the lab slides provided by the TAs are extremely helpful for visualization, so you may want to relook into it.

**Comment by GarlicButterSteak** [comment]
Thank you for the help everyone! I will try out your comments and work on the lab again!

**Comment by GarlicButterSteak** [comment]
After a terrible midnight marathon with the great assistance above and a proper reading of slides, indeed, a comparator class is necessary, though I think I also found out why I obtained the error --- my comparator class was missing a statement to return 0, so it seems that returning only 1 or -1 is insufficient. This is not a guaranteed diagnosis, but hopefully of any help to anyone who is reading this!
