### ISSUE TITLE
Removal of perfs file output on code crunch

### ISSUE THREAD

**Issue by kingofburg** [nus-cs2030/2223-s1#63]
When i submitted my file in code crunch, it gave this two lines:
![image](https://user-images.githubusercontent.com/110805343/189616406-ea766913-c5a2-4532-88ed-ac8d4df03725.png)
As a result, I failed my evaluation :(. Does anyone know what these prefs files are? Submission ID: 2362191

**Comment by danqiye1** [comment]
Hi, if you open your SolidImpl.java in vim, you will see an additional magic character behind your `private final Shape3D shape;`. Did you use a different editor other than vim to write this code?

**Comment by kingofburg** [comment]
I did use vim though, but thanks that did fix the problem!
