### ISSUE TITLE
Lab 3 PriorityQueue

### ISSUE THREAD

**Issue by szchew** [nus-cs2030/2223-s1#64]
I understand that we are supposed to process the different events in Lab 3. Is there a way for us to selectively choose certain events to be added back into the PriorityQueue after processing them? Any hints are appreciated!

**Comment by junhuiii** [comment]
If I understood your question correctly, I think you want to add all events which aren't DoneEvent back into the PQ for further processing? 
In this case, I guess the hint would be to think about what DoneEvent should give you after you have processed it.

**Comment by YEETTTTTTT** [comment]
Do you mean adding events back after they have been polled? You can create a variable that references the polled object, then re-add it back into the queue. However, you do not need to re-process events for this lab.

**Comment by bryanolm99** [comment]
From the lab slides, we know that every `Event` has a method `execute()` to return the next `Event`. For events like `Leave` and `Done`, how can you implement `execute()` (i.e. what `Event` should you return) so that you can easily determine if the newly returned `Event` is useless? (thus you don't have to add these new events back into the PQ)

**Comment by MingFengC** [comment]
Think of the state of an event before and after you call your method to process it.

**Comment by bransometan** [comment]
> From the lab slides, we know that every `Event` has a method `execute()` to return the next `Event`. For events like `Leave` and `Done`, how can you implement `execute()` (i.e. what `Event` should you return) so that you can easily determine if the newly returned `Event` is useless? (thus you don't have to add these new events back into the PQ)

For Leave Event and Done event, what I did was to check for their respective conditions (e.g. server is busy, etc). Then if the conditions are met, I just polled the priority queue to return the subsequent events.

**Comment by GarlicButterSteak** [comment]
For myself, I declared a boolean property for the parent event class to help selectively facilitate whether event instances need to be further processed and therefore whether they need to be added back into the queue. Hopefully, this may be of some help, and if it is, what remains is to determine how each type of event will be constructed with its _relevant_ boolean property 😄

**Comment by kohlindy** [comment]
Poll the queue to retrieve the current event, then check if there is a next event. If there is, use a nextEvent method to get the next event and add this next event into the queue. Repeat till the queue is empty.

**Comment by szchew** [comment]
I have tried another approach which is to enable polymorphic behaviour when updating PQ after processing the different events. However, I got this error instead.

PQ used in multiple classes.
Grading terminated.

Is there a better way of doing this?

**Comment by mohddanesh** [comment]
i have similar solution as @GarlicButterSteak and @kohlindy to check for event state

**Comment by szchew** [comment]
Thanks everyone! Somehow I have managed to solve this!
