### ISSUE TITLE
Difference Between Labs & Exercises

### ISSUE THREAD

**Issue by GarlicButterSteak** [nus-cs2030/2223-s1#7]
Hi, what is the difference between the exercises uploaded on CodeCrunch and lab sessions? Do we submit the exercises during lab? (Sorry, don’t have much experience with computing modules!)

**Comment by danqiye1** [comment]
Hello. The exercises are a set of graded self practices that you are to do on your own to reinforce and test whether you have grasped the concepts. The labs are like exercises, but they are conducted in labs with your lab tutors so you can ask them questions and they are a bit more guided. 

You don't work on exercises during labs. There will be a different problem set for you to do.

**Comment by GarlicButterSteak** [comment]
Thank you for the reply! Just to verify, may I know which grading component the lab problem sets will fall under? Thanks again!

**Comment by hwkchia** [comment]
It falls under project.
