### ISSUE TITLE
Exercise 4 ImList of ImList

### ISSUE THREAD

**Issue by yewey2** [nus-cs2030/2223-s1#74]
Do I need to do a ImList of ImList...? That's my first instinct but it seems to be very hard to implement, and unnecessarily change ImList code

**Comment by zhanyi3** [comment]
hi I thought of the same thing initially and yes it will be very hard to implement and also you will run into problems later on when trying to implement your `class Puzzle` . It will be better if you simply do the formatting in your toString to get the necessary output but leave your `Grid2D` as a simple `ImList`

**Comment by chiralcentre** [comment]
ImList of ImList is possible but I did it using one ImList

**Comment by Wenbo-J** [comment]
> 

Could you explain a little bit why it's not exactly hard to implement? I tried it using OP's said method and I am struggling badly with the add() method    :(

**Comment by yewey2** [comment]
> > 
> 
> Could you explain a little bit why it's not exactly hard to implement? I tried it using OP's said method and I am struggling badly with the add() method :(

lol did it with just the toString method, got A. no need to touch ImList at all :D

**Comment by wilsonwid** [comment]
@Wenbo-J 
For `Grid2D::add()` to be easier, you'll need a certain 'trick' that requires you to implement a similar constructor to `Grid2D(List<E> list, int numOfCols)`.

**Comment by Wenbo-J** [comment]
> > > 
> > 
> > 
> > Could you explain a little bit why it's not exactly hard to implement? I tried it using OP's said method and I am struggling badly with the add() method :(
> 
> lol did it with just the toString method, got A. no need to touch ImList at all :D

Lol I can imagine how much less troublesome it'd be if I were to restart with a single ImList and just manipulate the toString hhaha

**Comment by Wenbo-J** [comment]
> @Wenbo-J
For Grid2D::add() to be easier, you'll need a certain 'trick' that requires you to implement a similar constructor to Grid2D(List<E> list, int numOfCols).

Perhaps a constructor that takes in a Grid2D or an ImList of ImList?
But the time complexity might suffer right?

**Comment by wilsonwid** [comment]
@Wenbo-J 
Those are reasonable guesses!
Time complexity shouldn't be an issue in this module, unlike in CS2040.

**Comment by Wenbo-J** [comment]
> Those are reasonable guesses!
Time complexity shouldn't be an issue in this module, unlike in CS2040.

@wilsonwid 
Alrighty hhahah i'll go and try

**Comment by ccheemeng** [comment]
For more detail on Wilson's suggestion, #65 discusses solutions more explicitly!
