### ISSUE TITLE
use of restricted API (Object)

### ISSUE THREAD

**Issue by felibunnyy** [nus-cs2030/2223-s1#77]
I got a compilation error for lab 3 saying that I used the Object API, which is restricted. However, im not sure where I might have accidentally misused in my code. Does anyone know how to solve this issue?

<img width="406" alt="Screenshot 2022-09-15 at 3 40 46 AM" src="https://user-images.githubusercontent.com/105587981/190247226-f8c82758-a8a0-4aab-9063-ef336421c857.png">

**Comment by mohddanesh** [comment]
I think if you might have used some constant without declaring them as static

**Comment by eLTehh** [comment]
Did you import java.util.*? It basically imports everything under java.util, which includes Objects. Might want to keep it to java.util.(specific class you're importing)

**Comment by Wenbo-J** [comment]
you perhaps have included constants without the static keyword, or perhaps you have public keyword in front of a non-driver class?

**Comment by danqiye1** [comment]
Has this been resolved? If not, please provide submission id for us to take a look.
