### ISSUE TITLE
Lab #4 level 5

### ISSUE THREAD

**Issue by zhanyi3** [nus-cs2030/2223-s1#81]
regarding `class Booking` , in level 3 it is stated _"add a Booking class that takes in a driver and a request. From the services that a driver provides, the best service with the lowest fare is selected."_ then in level 5, I see that we are supposed to output `Booking` for all services provided by each driver. I have no idea how to go about it given that the `toString()` method of `Booking` is meant to only produce the cheapest service. Does anyone know how do I go about this?

**Comment by nguyenvukhang** [comment]
One possible way is to return all possible services from the booking, and handle printing outside of the `Booking` class.

**Comment by MingFengC** [comment]
As you mentioned, your current `toString()` method is limited to returning the cheapest service. One possible way would be to not involve your `bestService()` method in your `toString()` method and relook at your constructors.

After which you would:
1. Return and store all bookings
2. Depending on your implementation, you can handle the order of the output w.r.t the constraint of the `compareTo(Booking secondBooking)` method

**Comment by bryanolm99** [comment]
I created another class to represent every match in each `Booking`. I also implemented the `compareTo()` method and `Comparator` for this new class. This is useful for level 5, where the order of output is independent of the `Booking`  each match belongs to, but rather depends on the rules of (i) lowest fare and (ii) waiting time.

You may then also delegate your `Booking` class's `compareTo()` method to the `compareTo()` method defined above. Your `toString()` method under `Booking` class would then just need to be concerned with the best match.

**Comment by bransometan** [comment]
I have exactly the same problem as you but I changed my implementation to accommodate level 5 by not putting the method to find the best service inside `toString()` method. Instead, I modified Booking class to track the state of the current 'service'. By doing this, I can pass in any services to this Booking class and it can return the specific booking fare for that service. As for level 3, I just instantiate the Booking class with the best service for the current 'service' state as default.

> regarding `class Booking` , in level 3 it is stated _"add a Booking class that takes in a driver and a request. From the services that a driver provides, the best service with the lowest fare is selected."_ then in level 5, I see that we are supposed to output `Booking` for all services provided by each driver. I have no idea how to go about it given that the `toString()` method of `Booking` is meant to only produce the cheapest service. Does anyone know how do I go about this?

**Comment by zhanyi3** [comment]
thanks for all the suggestions guys! it was very helpful :)
