### ISSUE TITLE
[Project #1] Not understanding the logic behind the Expected Output for Test Case 7

### ISSUE THREAD

**Issue by axmszr** [nus-cs2030/2223-s1#83]
# Summary
From what I can gather, this test case seems to involve 1 `Server` with `qmax` 1 (i.e. the first line is `1 1`). However, `Customers` 2 and 3 seem to somehow be processed cocurrently in the expected output, which doesn't make much sense to me. Please refer to the screenshot below.

- Lines 3-6: Even if the `Arrive` events of `Customers` 2 and 3 are to be processed back-to-back (which doesn't feel quite right), since they are different `Customers`, does this not break the `qmax` rule? This is discrete event simulator; the triggers from state to state are `Events`. Shouldn't these two distinct `Events` thus be treated distinctly?
- Lines 14-15: Similarly, how are both of them being served at the same time? The task content explicitly says "Each server can serve one customer at a time", so like...

There are a few more problems further down, but I suspect they are just snowballed issues.

Am I misunderstanding the problem statement? I'd appreciate any clarification! Thank you very much.

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/72402917/190833994-f96a1153-aef9-4ee8-bd0f-ae38fc34ff0b.png)

**Comment by hwkchia** [comment]
I've since amended the test cases and regraded. 😃

**Comment by axmszr** [comment]
> I've since amended the test cases and regraded. 😃

Ah, noted with thanks Prof!
