### ISSUE TITLE
Lab 4 Level 3 Unexpected Output

### ISSUE THREAD

**Issue by quek-zhiheng** [nus-cs2030/2223-s1#85]
# Summary
Hi! Am facing some small issues over here because I think my code should be working fine, but when I ran the code on JShell, it is giving me an empty line as an output, not sure if anyone faced this issue and managed to resolve it somehow? Thanks in advance!

[Edit: seems to work on CodeCrunch nevertheless, will close the issue!]

## Screenshots

![IMAGE 2022-09-17 13:16:40](https://user-images.githubusercontent.com/64345784/190841690-dfb21bd8-143e-4c62-874f-0847ccda8d81.jpg)

**Comment by wilsonwid** [comment]
If you're using `String.format()`, the bug might come from there, because I was facing issues similar to yours :)

**Comment by quek-zhiheng** [comment]
Oh I see, I did use `String.format()` to pad 0s but this didn't really occur to me as a few exercises ago we were also using it, thanks for the reply! 😄
