### ISSUE TITLE
Overloading, Polymorphism and Interfaces

### ISSUE THREAD

**Issue by SungMatt** [nus-cs2030/2223-s1#87]
Say I am creating a polymorphic method -- one that has no inputs, and one that takes in an input. Then suppose that this behavior is expected for multiple classes -- so I make an interface for all of these methods.

In the interface, I'm unable to create a polymorphic method, without each of the implementing classes implementing both polymorphic methods. Is there a way to specify in the interface that the method can come in **either** form?

**Comment by mohddanesh** [comment]
i don't think the method a class get from interface can be selected. How about create more interface instead with each of them doing 1 particular thing?

**Comment by SungMatt** [comment]
Hey all, thanks for the responses! Understand the issue now!
