### ISSUE TITLE
Questions about upcoming PA

### ISSUE THREAD

**Issue by zccccclin** [nus-cs2030/2223-s1#88]
Hi all, I have the following questions about the upcoming PA.

1. Will Immutable ImList and Pair be provided during PA?

2. What are the available imports we can and cannot use during PA?
I understand that all the mutable imports are not allowed, how about things like java.util.List.

**Comment by kohlindy** [comment]
I think we are not allowed to use java libraries, other than those from java.lang, java.util.List and java.util.Comparator.

**Comment by ShiJiaAo** [comment]
am also wondering if ImList.java will be provided during the PA if we need to use it
