### ISSUE TITLE
Self Practice 2 - Level 2

### ISSUE THREAD

**Issue by yqlok17** [nus-cs2030/2223-s1#89]
So I'm currently attempting Self-Practice 2 and I don't understand how to go about solving the algorithm part of Level 2 for the nextLoader method.

From what I understand from this question, numOfLoaders already tells us how many loaders are the in the set of loaders, and the identifier indicates the loader number. I don't quite get how the constructor works - it says it creates a set and returns the set's first loader, so are we creating something like an Array of loaders in this case? I've seen the thread from #44 stating it is unnecessary but I don't quite understand what is going on here still. 

I understand the toString method returns the string "Loader #" with it's identifier. But I'm not sure where to proceed from here subsequently, does nextLoader require a counter variable that modifies the identifier as we cycle through the loaders (yet the identifier is immutable)? 

Would like to seek some clarification on this part.

**Comment by junhuiii** [comment]
Notice that when we call the next loader, we don't go back to the previous loadeer anymore unless we have reached the maximum number of loaders specified in the constructor. 

In this case, there's really no need to the maintain an arraylist. All you have to do is ensure that each loader can call the next loader, and also ensure that if you are calling the last loader, the next loader should be the very first loader, **although it doesn't have to be the same object.** 

Hope that helps!

**Comment by KEEWEIKUANG** [comment]
In my opinion, i feel that In the NextLoader() method, you might want to think of an if else statement whereby when it go past the required loaders, it will return back to the first loader. You might also want to think of how you want to return the Loader object with a condition whereby how to get back to the first loader when it go past the required loaders.

**Comment by mohddanesh** [comment]
I agree that there is no need to use ArrayList to store loaders. Just simply increment the number every time you call nextLoader. If it is beyond the number of loaders initialized, return to 1.

**Comment by ccheemeng** [comment]
Every loader should be able to return a new loader object with its nextLoader() method, and the new loader's identifier should either be +1 from the first loader's identifier, or reset to 1 if the first loader's identifier is equal to numOfLoaders. I feel that the instruction that a "set" of loaders is created with `new Loader(n)` is a bit misleading, in the sense that in the actual implementation, `new Loader(n)` really only needs to create one loader.

**Comment by yqlok17** [comment]
Have figured out the solution, thanks to everyone giving input!
