### ISSUE TITLE
Exercise 3: update replaced variable solidcuboid which cannot be referenced until class SolidCuboid is declared

### ISSUE THREAD

**Issue by jingyiiiiz** [nus-cs2030/2223-s1#91]
I didn't quite understand the instructions for the last level and got something like this in my output:

![Screen Shot 2022-09-19 at 12 03 34 AM](https://user-images.githubusercontent.com/105194164/190916616-a6818625-8571-4025-bcd6-c5fedfd9dc0b.png)

May I ask why this error arises and how it can be addressed? Thanks in advance!

**Comment by xuan-jun** [comment]
Hello, I think you can refer to #36, the issue is that you did not delegate the computation of the `mass()` to `SolidImpl` properly in your `SolidCuboid`. Hope this helps!

**Comment by keefetok** [comment]
xuan-jun got it, i think this is a testcase by prof to see if you followed design spec? so in this case, delegating the computation of mass() solely to SolidImpl (as stated in question).
