### ISSUE TITLE
Lab 04 Level 5 output format

### ISSUE THREAD

**Issue by BBBoyu** [nus-cs2030/2223-s1#92]
# Summary

My output for lab 04 test case 5 is slightly different from the expected output.  I understand that it may be due to the ImList.toString() method, but I can't seem to think of a way to get rid of the bracket and the comma. Does anyone know how to address the issue? Thanks in advance!

## Screenshots

![3](https://user-images.githubusercontent.com/105358038/190923148-0b607aa5-2ded-402a-8359-901869a9a2b0.PNG)

**Comment by XihuaZ** [comment]
Thats because u printed out a list rather than printing individual elements within the list. U need to call individual elems within the ImList

**Comment by jingyiiiiz** [comment]
I think you can iterate through the list and print out each items individually

**Comment by BBBoyu** [comment]
Thank you for your suggestions!
