### ISSUE TITLE
Lab 4 Test Case 5

### ISSUE THREAD

**Issue by XihuaZ** [nus-cs2030/2223-s1#93]
I am unsure what is generating this problem. I am able to get the same output as shown in Level 5.

<img width="1175" alt="Screenshot 2022-09-19 at 04 13 04" src="https://user-images.githubusercontent.com/91673283/190926581-f4410ae2-fee6-4cd2-a9fd-c918b7cf7499.png">

**Comment by shecheeyee** [comment]
Hi! May I know how you resolved this? Am facing this issue as well, thanks!
