### ISSUE TITLE
reversed output for lab 4 

### ISSUE THREAD

**Issue by keefetok** [nus-cs2030/2223-s1#95]
![2022-09-19 17 36 21](https://user-images.githubusercontent.com/50988301/190990009-431b73b4-42c6-4e99-8c99-75db10fbd9ed.jpg)

hi does anyone know what is happening here? i have the outputs but they are reversed...

i passed all test cases and can pass this "test3" on my compiler too 

Screenshots (if any)

**Comment by OngMinXian** [comment]
Hello! I faced this issue too. Turns out my compareTo method was wrong and I reversed the outputs for when comparing the best fares.
