### ISSUE TITLE
[Project #1] Using static fields to store simulation statistics

### ISSUE THREAD

**Issue by bryanolm99** [nus-cs2030/2223-s1#96]
Since the task requires us to keep track of simulation statistics across all events, I thought that a convenient way would be to store them as static fields under `Event`. As a result, these static fields cannot be declared final. But the codecrunch checker requires them to be declared final.

Are we banned from using static fields in this project or am I using static fields wrongly in this case? Thanks!

**Comment by wilsonwid** [comment]
I don't think you need `static` attributes when you can set similar variable(s) in `Simulator::simulate()`, albeit you will maybe need to implement additional methods.

**Comment by OngMinXian** [comment]
Hey Bryan I don't know if you need help for this but
what I did was have each of my event subclasses have 2 methods that return double wait time and int 1 (if asked customer to leave). If they are not the relevent events in calculating the statistics, I simply returned 0. Hope this helps

**Comment by bryanolm99** [comment]
Thanks for the inputs! I did it by passing the statistics as parameters into each event and returning the updated statistics. But I'm still curious to know if the use of static fields is inappropriate since the lecture notes mentioned that a good use of them would be to store aggregated data (like the statistics in our case).

**Comment by danqiye1** [comment]
@bryanolm99, in CS2030 we do allow the use of static fields but like you said they must be `final` as we want to enforce immutability to prevent insidious bugs (like if you modified the static fields in some other methods but you thought your old reference to the statistics are still not updated). 

You can still update `Statistics` with the following patterns of methods:
```java
class Statistic {
    private final int x;
    Statistic update(Statistic stats) {
        return new Statistic(stats.x + 1);
    }
}
```
