### ISSUE TITLE
Lab 4: Suggestions for implementation

### ISSUE THREAD

**Issue by mersoncheong** [nus-cs2030/2223-s1#98]
# Summary

Hey guys! I am having some trouble passing this private test case which I believe wishes to extend my classes. I would appreciate some advice on how I could tweak my implementation to support this. 

## Description:

Private Test Case creates a new Driver `PrivateCarX` which offers its own service `ShareARideX`. My code currently only takes into account to 2 given classes `PrivateCar` and `NormalCab` which I explicitly link to the services they provide directly. This is probably the cause of this problem. How did you guys manage to get around? Thanks in advance! 

## Screenshots

![123](https://user-images.githubusercontent.com/79396071/191213878-dd2c9dec-2cbc-463f-ba70-f59c442035fb.PNG)

**Comment by mohddanesh** [comment]
Do you have a Service class that is the parent of different types of service like ShareARide? Do you also store an attribute of the Service class in the Booking class to return the the Service class directly in the toString of Booking class?

**Comment by mersoncheong** [comment]
Thanks for your help! @yewey2 @mohddanesh
